export interface Country {
  code: string;
  name: string;
  flag: string;
  flagImageUrl: string;
  region: string;
}

export interface CountryOption {
  value: string;
  label: string;
  code: string;
  flag: string;
  flagImageUrl: string;
  region: string;
}

/**
 * Generate flag image URL from country code
 * Uses flagcdn.com CDN for flag images
 */
export const getFlagImageUrl = (
  code: string,
  size: "w20" | "w40" | "w80" | "w160" | "w320" = "w40"
): string => {
  const lowerCode = code.toLowerCase();
  return `https://flagcdn.com/${size}/${lowerCode}.png`;
};

export const COUNTRIES: Country[] = [
  {
    code: "AF",
    name: "Afghanistan",
    flag: "🇦🇫",
    flagImageUrl: getFlagImageUrl("AF"),
    region: "Asia",
  },
  {
    code: "AL",
    name: "Albania",
    flag: "🇦🇱",
    flagImageUrl: getFlagImageUrl("AL"),
    region: "Europe",
  },
  {
    code: "DZ",
    name: "Algeria",
    flag: "🇩🇿",
    flagImageUrl: getFlagImageUrl("DZ"),
    region: "Africa",
  },
  {
    code: "AD",
    name: "Andorra",
    flag: "🇦🇩",
    flagImageUrl: getFlagImageUrl("AD"),
    region: "Europe",
  },
  {
    code: "AO",
    name: "Angola",
    flag: "🇦🇴",
    flagImageUrl: getFlagImageUrl("AO"),
    region: "Africa",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    flagImageUrl: getFlagImageUrl("AG"),
    region: "Americas",
  },
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    flagImageUrl: getFlagImageUrl("AR"),
    region: "Americas",
  },
  {
    code: "AM",
    name: "Armenia",
    flag: "🇦🇲",
    flagImageUrl: getFlagImageUrl("AM"),
    region: "Asia",
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    flagImageUrl: getFlagImageUrl("AU"),
    region: "Oceania",
  },
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    flagImageUrl: getFlagImageUrl("AT"),
    region: "Europe",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    flag: "🇦🇿",
    flagImageUrl: getFlagImageUrl("AZ"),
    region: "Asia",
  },
  {
    code: "BS",
    name: "Bahamas",
    flag: "🇧🇸",
    flagImageUrl: getFlagImageUrl("BS"),
    region: "Americas",
  },
  {
    code: "BH",
    name: "Bahrain",
    flag: "🇧🇭",
    flagImageUrl: getFlagImageUrl("BH"),
    region: "Asia",
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    flagImageUrl: getFlagImageUrl("BD"),
    region: "Asia",
  },
  {
    code: "BB",
    name: "Barbados",
    flag: "🇧🇧",
    flagImageUrl: getFlagImageUrl("BB"),
    region: "Americas",
  },
  {
    code: "BY",
    name: "Belarus",
    flag: "🇧🇾",
    flagImageUrl: getFlagImageUrl("BY"),
    region: "Europe",
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    flagImageUrl: getFlagImageUrl("BE"),
    region: "Europe",
  },
  {
    code: "BZ",
    name: "Belize",
    flag: "🇧🇿",
    flagImageUrl: getFlagImageUrl("BZ"),
    region: "Americas",
  },
  {
    code: "BJ",
    name: "Benin",
    flag: "🇧🇯",
    flagImageUrl: getFlagImageUrl("BJ"),
    region: "Africa",
  },
  {
    code: "BT",
    name: "Bhutan",
    flag: "🇧🇹",
    flagImageUrl: getFlagImageUrl("BT"),
    region: "Asia",
  },
  {
    code: "BO",
    name: "Bolivia",
    flag: "🇧🇴",
    flagImageUrl: getFlagImageUrl("BO"),
    region: "Americas",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    flagImageUrl: getFlagImageUrl("BA"),
    region: "Europe",
  },
  {
    code: "BW",
    name: "Botswana",
    flag: "🇧🇼",
    flagImageUrl: getFlagImageUrl("BW"),
    region: "Africa",
  },
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    flagImageUrl: getFlagImageUrl("BR"),
    region: "Americas",
  },
  {
    code: "BN",
    name: "Brunei",
    flag: "🇧🇳",
    flagImageUrl: getFlagImageUrl("BN"),
    region: "Asia",
  },
  {
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    flagImageUrl: getFlagImageUrl("BG"),
    region: "Europe",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
    flagImageUrl: getFlagImageUrl("BF"),
    region: "Africa",
  },
  {
    code: "BI",
    name: "Burundi",
    flag: "🇧🇮",
    flagImageUrl: getFlagImageUrl("BI"),
    region: "Africa",
  },
  {
    code: "CV",
    name: "Cabo Verde",
    flag: "🇨🇻",
    flagImageUrl: getFlagImageUrl("CV"),
    region: "Africa",
  },
  {
    code: "KH",
    name: "Cambodia",
    flag: "🇰🇭",
    flagImageUrl: getFlagImageUrl("KH"),
    region: "Asia",
  },
  {
    code: "CM",
    name: "Cameroon",
    flag: "🇨🇲",
    flagImageUrl: getFlagImageUrl("CM"),
    region: "Africa",
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    flagImageUrl: getFlagImageUrl("CA"),
    region: "Americas",
  },
  {
    code: "CF",
    name: "Central African Republic",
    flag: "🇨🇫",
    flagImageUrl: getFlagImageUrl("CF"),
    region: "Africa",
  },
  {
    code: "TD",
    name: "Chad",
    flag: "🇹🇩",
    flagImageUrl: getFlagImageUrl("TD"),
    region: "Africa",
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    flagImageUrl: getFlagImageUrl("CL"),
    region: "Americas",
  },
  {
    code: "CN",
    name: "China",
    flag: "🇨🇳",
    flagImageUrl: getFlagImageUrl("CN"),
    region: "Asia",
  },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    flagImageUrl: getFlagImageUrl("CO"),
    region: "Americas",
  },
  {
    code: "KM",
    name: "Comoros",
    flag: "🇰🇲",
    flagImageUrl: getFlagImageUrl("KM"),
    region: "Africa",
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    flag: "🇨🇩",
    flagImageUrl: getFlagImageUrl("CD"),
    region: "Africa",
  },
  {
    code: "CG",
    name: "Congo, Republic of the",
    flag: "🇨🇬",
    flagImageUrl: getFlagImageUrl("CG"),
    region: "Africa",
  },
  {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    flagImageUrl: getFlagImageUrl("CR"),
    region: "Americas",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    flagImageUrl: getFlagImageUrl("CI"),
    region: "Africa",
  },
  {
    code: "HR",
    name: "Croatia",
    flag: "🇭🇷",
    flagImageUrl: getFlagImageUrl("HR"),
    region: "Europe",
  },
  {
    code: "CU",
    name: "Cuba",
    flag: "🇨🇺",
    flagImageUrl: getFlagImageUrl("CU"),
    region: "Americas",
  },
  {
    code: "CY",
    name: "Cyprus",
    flag: "🇨🇾",
    flagImageUrl: getFlagImageUrl("CY"),
    region: "Europe",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    flag: "🇨🇿",
    flagImageUrl: getFlagImageUrl("CZ"),
    region: "Europe",
  },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    flagImageUrl: getFlagImageUrl("DK"),
    region: "Europe",
  },
  {
    code: "DJ",
    name: "Djibouti",
    flag: "🇩🇯",
    flagImageUrl: getFlagImageUrl("DJ"),
    region: "Africa",
  },
  {
    code: "DM",
    name: "Dominica",
    flag: "🇩🇲",
    flagImageUrl: getFlagImageUrl("DM"),
    region: "Americas",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    flag: "🇩🇴",
    flagImageUrl: getFlagImageUrl("DO"),
    region: "Americas",
  },
  {
    code: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
    flagImageUrl: getFlagImageUrl("EC"),
    region: "Americas",
  },
  {
    code: "EG",
    name: "Egypt",
    flag: "🇪🇬",
    flagImageUrl: getFlagImageUrl("EG"),
    region: "Africa",
  },
  {
    code: "SV",
    name: "El Salvador",
    flag: "🇸🇻",
    flagImageUrl: getFlagImageUrl("SV"),
    region: "Americas",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    flagImageUrl: getFlagImageUrl("GQ"),
    region: "Africa",
  },
  {
    code: "ER",
    name: "Eritrea",
    flag: "🇪🇷",
    flagImageUrl: getFlagImageUrl("ER"),
    region: "Africa",
  },
  {
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    flagImageUrl: getFlagImageUrl("EE"),
    region: "Europe",
  },
  {
    code: "SZ",
    name: "Eswatini",
    flag: "🇸🇿",
    flagImageUrl: getFlagImageUrl("SZ"),
    region: "Africa",
  },
  {
    code: "ET",
    name: "Ethiopia",
    flag: "🇪🇹",
    flagImageUrl: getFlagImageUrl("ET"),
    region: "Africa",
  },
  {
    code: "FJ",
    name: "Fiji",
    flag: "🇫🇯",
    flagImageUrl: getFlagImageUrl("FJ"),
    region: "Oceania",
  },
  {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    flagImageUrl: getFlagImageUrl("FI"),
    region: "Europe",
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    flagImageUrl: getFlagImageUrl("FR"),
    region: "Europe",
  },
  {
    code: "GA",
    name: "Gabon",
    flag: "🇬🇦",
    flagImageUrl: getFlagImageUrl("GA"),
    region: "Africa",
  },
  {
    code: "GM",
    name: "Gambia",
    flag: "🇬🇲",
    flagImageUrl: getFlagImageUrl("GM"),
    region: "Africa",
  },
  {
    code: "GE",
    name: "Georgia",
    flag: "🇬🇪",
    flagImageUrl: getFlagImageUrl("GE"),
    region: "Asia",
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    flagImageUrl: getFlagImageUrl("DE"),
    region: "Europe",
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    flagImageUrl: getFlagImageUrl("GH"),
    region: "Africa",
  },
  {
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    flagImageUrl: getFlagImageUrl("GR"),
    region: "Europe",
  },
  {
    code: "GD",
    name: "Grenada",
    flag: "🇬🇩",
    flagImageUrl: getFlagImageUrl("GD"),
    region: "Americas",
  },
  {
    code: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
    flagImageUrl: getFlagImageUrl("GT"),
    region: "Americas",
  },
  {
    code: "GN",
    name: "Guinea",
    flag: "🇬🇳",
    flagImageUrl: getFlagImageUrl("GN"),
    region: "Africa",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    flagImageUrl: getFlagImageUrl("GW"),
    region: "Africa",
  },
  {
    code: "GY",
    name: "Guyana",
    flag: "🇬🇾",
    flagImageUrl: getFlagImageUrl("GY"),
    region: "Americas",
  },
  {
    code: "HT",
    name: "Haiti",
    flag: "🇭🇹",
    flagImageUrl: getFlagImageUrl("HT"),
    region: "Americas",
  },
  {
    code: "HN",
    name: "Honduras",
    flag: "🇭🇳",
    flagImageUrl: getFlagImageUrl("HN"),
    region: "Americas",
  },
  {
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    flagImageUrl: getFlagImageUrl("HU"),
    region: "Europe",
  },
  {
    code: "IS",
    name: "Iceland",
    flag: "🇮🇸",
    flagImageUrl: getFlagImageUrl("IS"),
    region: "Europe",
  },
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    flagImageUrl: getFlagImageUrl("IN"),
    region: "Asia",
  },
  {
    code: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    flagImageUrl: getFlagImageUrl("ID"),
    region: "Asia",
  },
  {
    code: "IR",
    name: "Iran",
    flag: "🇮🇷",
    flagImageUrl: getFlagImageUrl("IR"),
    region: "Asia",
  },
  {
    code: "IQ",
    name: "Iraq",
    flag: "🇮🇶",
    flagImageUrl: getFlagImageUrl("IQ"),
    region: "Asia",
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    flagImageUrl: getFlagImageUrl("IE"),
    region: "Europe",
  },
  {
    code: "IL",
    name: "Israel",
    flag: "🇮🇱",
    flagImageUrl: getFlagImageUrl("IL"),
    region: "Asia",
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    flagImageUrl: getFlagImageUrl("IT"),
    region: "Europe",
  },
  {
    code: "JM",
    name: "Jamaica",
    flag: "🇯🇲",
    flagImageUrl: getFlagImageUrl("JM"),
    region: "Americas",
  },
  {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    flagImageUrl: getFlagImageUrl("JP"),
    region: "Asia",
  },
  {
    code: "JO",
    name: "Jordan",
    flag: "🇯🇴",
    flagImageUrl: getFlagImageUrl("JO"),
    region: "Asia",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    flag: "🇰🇿",
    flagImageUrl: getFlagImageUrl("KZ"),
    region: "Asia",
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    flagImageUrl: getFlagImageUrl("KE"),
    region: "Africa",
  },
  {
    code: "KI",
    name: "Kiribati",
    flag: "🇰🇮",
    flagImageUrl: getFlagImageUrl("KI"),
    region: "Oceania",
  },
  {
    code: "KP",
    name: "Korea, North",
    flag: "🇰🇵",
    flagImageUrl: getFlagImageUrl("KP"),
    region: "Asia",
  },
  {
    code: "KR",
    name: "Korea, South",
    flag: "🇰🇷",
    flagImageUrl: getFlagImageUrl("KR"),
    region: "Asia",
  },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    flagImageUrl: getFlagImageUrl("KW"),
    region: "Asia",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    flagImageUrl: getFlagImageUrl("KG"),
    region: "Asia",
  },
  {
    code: "LA",
    name: "Laos",
    flag: "🇱🇦",
    flagImageUrl: getFlagImageUrl("LA"),
    region: "Asia",
  },
  {
    code: "LV",
    name: "Latvia",
    flag: "🇱🇻",
    flagImageUrl: getFlagImageUrl("LV"),
    region: "Europe",
  },
  {
    code: "LB",
    name: "Lebanon",
    flag: "🇱🇧",
    flagImageUrl: getFlagImageUrl("LB"),
    region: "Asia",
  },
  {
    code: "LS",
    name: "Lesotho",
    flag: "🇱🇸",
    flagImageUrl: getFlagImageUrl("LS"),
    region: "Africa",
  },
  {
    code: "LR",
    name: "Liberia",
    flag: "🇱🇷",
    flagImageUrl: getFlagImageUrl("LR"),
    region: "Africa",
  },
  {
    code: "LY",
    name: "Libya",
    flag: "🇱🇾",
    flagImageUrl: getFlagImageUrl("LY"),
    region: "Africa",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    flag: "🇱🇮",
    flagImageUrl: getFlagImageUrl("LI"),
    region: "Europe",
  },
  {
    code: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
    flagImageUrl: getFlagImageUrl("LT"),
    region: "Europe",
  },
  {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    flagImageUrl: getFlagImageUrl("LU"),
    region: "Europe",
  },
  {
    code: "MG",
    name: "Madagascar",
    flag: "🇲🇬",
    flagImageUrl: getFlagImageUrl("MG"),
    region: "Africa",
  },
  {
    code: "MW",
    name: "Malawi",
    flag: "🇲🇼",
    flagImageUrl: getFlagImageUrl("MW"),
    region: "Africa",
  },
  {
    code: "MY",
    name: "Malaysia",
    flag: "🇲🇾",
    flagImageUrl: getFlagImageUrl("MY"),
    region: "Asia",
  },
  {
    code: "MV",
    name: "Maldives",
    flag: "🇲🇻",
    flagImageUrl: getFlagImageUrl("MV"),
    region: "Asia",
  },
  {
    code: "ML",
    name: "Mali",
    flag: "🇲🇱",
    flagImageUrl: getFlagImageUrl("ML"),
    region: "Africa",
  },
  {
    code: "MT",
    name: "Malta",
    flag: "🇲🇹",
    flagImageUrl: getFlagImageUrl("MT"),
    region: "Europe",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    flag: "🇲🇭",
    flagImageUrl: getFlagImageUrl("MH"),
    region: "Oceania",
  },
  {
    code: "MR",
    name: "Mauritania",
    flag: "🇲🇷",
    flagImageUrl: getFlagImageUrl("MR"),
    region: "Africa",
  },
  {
    code: "MU",
    name: "Mauritius",
    flag: "🇲🇺",
    flagImageUrl: getFlagImageUrl("MU"),
    region: "Africa",
  },
  {
    code: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    flagImageUrl: getFlagImageUrl("MX"),
    region: "Americas",
  },
  {
    code: "FM",
    name: "Micronesia",
    flag: "🇫🇲",
    flagImageUrl: getFlagImageUrl("FM"),
    region: "Oceania",
  },
  {
    code: "MD",
    name: "Moldova",
    flag: "🇲🇩",
    flagImageUrl: getFlagImageUrl("MD"),
    region: "Europe",
  },
  {
    code: "MC",
    name: "Monaco",
    flag: "🇲🇨",
    flagImageUrl: getFlagImageUrl("MC"),
    region: "Europe",
  },
  {
    code: "MN",
    name: "Mongolia",
    flag: "🇲🇳",
    flagImageUrl: getFlagImageUrl("MN"),
    region: "Asia",
  },
  {
    code: "ME",
    name: "Montenegro",
    flag: "🇲🇪",
    flagImageUrl: getFlagImageUrl("ME"),
    region: "Europe",
  },
  {
    code: "MA",
    name: "Morocco",
    flag: "🇲🇦",
    flagImageUrl: getFlagImageUrl("MA"),
    region: "Africa",
  },
  {
    code: "MZ",
    name: "Mozambique",
    flag: "🇲🇿",
    flagImageUrl: getFlagImageUrl("MZ"),
    region: "Africa",
  },
  {
    code: "MM",
    name: "Myanmar (Burma)",
    flag: "🇲🇲",
    flagImageUrl: getFlagImageUrl("MM"),
    region: "Asia",
  },
  {
    code: "NA",
    name: "Namibia",
    flag: "🇳🇦",
    flagImageUrl: getFlagImageUrl("NA"),
    region: "Africa",
  },
  {
    code: "NR",
    name: "Nauru",
    flag: "🇳🇷",
    flagImageUrl: getFlagImageUrl("NR"),
    region: "Oceania",
  },
  {
    code: "NP",
    name: "Nepal",
    flag: "🇳🇵",
    flagImageUrl: getFlagImageUrl("NP"),
    region: "Asia",
  },
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    flagImageUrl: getFlagImageUrl("NL"),
    region: "Europe",
  },
  {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    flagImageUrl: getFlagImageUrl("NZ"),
    region: "Oceania",
  },
  {
    code: "NI",
    name: "Nicaragua",
    flag: "🇳🇮",
    flagImageUrl: getFlagImageUrl("NI"),
    region: "Americas",
  },
  {
    code: "NE",
    name: "Niger",
    flag: "🇳🇪",
    flagImageUrl: getFlagImageUrl("NE"),
    region: "Africa",
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    flagImageUrl: getFlagImageUrl("NG"),
    region: "Africa",
  },
  {
    code: "MK",
    name: "North Macedonia",
    flag: "🇲🇰",
    flagImageUrl: getFlagImageUrl("MK"),
    region: "Europe",
  },
  {
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    flagImageUrl: getFlagImageUrl("NO"),
    region: "Europe",
  },
  {
    code: "OM",
    name: "Oman",
    flag: "🇴🇲",
    flagImageUrl: getFlagImageUrl("OM"),
    region: "Asia",
  },
  {
    code: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
    flagImageUrl: getFlagImageUrl("PK"),
    region: "Asia",
  },
  {
    code: "PW",
    name: "Palau",
    flag: "🇵🇼",
    flagImageUrl: getFlagImageUrl("PW"),
    region: "Oceania",
  },
  {
    code: "PS",
    name: "Palestine",
    flag: "🇵🇸",
    flagImageUrl: getFlagImageUrl("PS"),
    region: "Asia",
  },
  {
    code: "PA",
    name: "Panama",
    flag: "🇵🇦",
    flagImageUrl: getFlagImageUrl("PA"),
    region: "Americas",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    flag: "🇵🇬",
    flagImageUrl: getFlagImageUrl("PG"),
    region: "Oceania",
  },
  {
    code: "PY",
    name: "Paraguay",
    flag: "🇵🇾",
    flagImageUrl: getFlagImageUrl("PY"),
    region: "Americas",
  },
  {
    code: "PE",
    name: "Peru",
    flag: "🇵🇪",
    flagImageUrl: getFlagImageUrl("PE"),
    region: "Americas",
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    flagImageUrl: getFlagImageUrl("PH"),
    region: "Asia",
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    flagImageUrl: getFlagImageUrl("PL"),
    region: "Europe",
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    flagImageUrl: getFlagImageUrl("PT"),
    region: "Europe",
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    flagImageUrl: getFlagImageUrl("QA"),
    region: "Asia",
  },
  {
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    flagImageUrl: getFlagImageUrl("RO"),
    region: "Europe",
  },
  {
    code: "RU",
    name: "Russia",
    flag: "🇷🇺",
    flagImageUrl: getFlagImageUrl("RU"),
    region: "Europe",
  },
  {
    code: "RW",
    name: "Rwanda",
    flag: "🇷🇼",
    flagImageUrl: getFlagImageUrl("RW"),
    region: "Africa",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    flagImageUrl: getFlagImageUrl("KN"),
    region: "Americas",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    flag: "🇱🇨",
    flagImageUrl: getFlagImageUrl("LC"),
    region: "Americas",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    flagImageUrl: getFlagImageUrl("VC"),
    region: "Americas",
  },
  {
    code: "WS",
    name: "Samoa",
    flag: "🇼🇸",
    flagImageUrl: getFlagImageUrl("WS"),
    region: "Oceania",
  },
  {
    code: "SM",
    name: "San Marino",
    flag: "🇸🇲",
    flagImageUrl: getFlagImageUrl("SM"),
    region: "Europe",
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    flagImageUrl: getFlagImageUrl("ST"),
    region: "Africa",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    flagImageUrl: getFlagImageUrl("SA"),
    region: "Asia",
  },
  {
    code: "SN",
    name: "Senegal",
    flag: "🇸🇳",
    flagImageUrl: getFlagImageUrl("SN"),
    region: "Africa",
  },
  {
    code: "RS",
    name: "Serbia",
    flag: "🇷🇸",
    flagImageUrl: getFlagImageUrl("RS"),
    region: "Europe",
  },
  {
    code: "SC",
    name: "Seychelles",
    flag: "🇸🇨",
    flagImageUrl: getFlagImageUrl("SC"),
    region: "Africa",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    flag: "🇸🇱",
    flagImageUrl: getFlagImageUrl("SL"),
    region: "Africa",
  },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    flagImageUrl: getFlagImageUrl("SG"),
    region: "Asia",
  },
  {
    code: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
    flagImageUrl: getFlagImageUrl("SK"),
    region: "Europe",
  },
  {
    code: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
    flagImageUrl: getFlagImageUrl("SI"),
    region: "Europe",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    flag: "🇸🇧",
    flagImageUrl: getFlagImageUrl("SB"),
    region: "Oceania",
  },
  {
    code: "SO",
    name: "Somalia",
    flag: "🇸🇴",
    flagImageUrl: getFlagImageUrl("SO"),
    region: "Africa",
  },
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    flagImageUrl: getFlagImageUrl("ZA"),
    region: "Africa",
  },
  {
    code: "SS",
    name: "South Sudan",
    flag: "🇸🇸",
    flagImageUrl: getFlagImageUrl("SS"),
    region: "Africa",
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    flagImageUrl: getFlagImageUrl("ES"),
    region: "Europe",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
    flagImageUrl: getFlagImageUrl("LK"),
    region: "Asia",
  },
  {
    code: "SD",
    name: "Sudan",
    flag: "🇸🇩",
    flagImageUrl: getFlagImageUrl("SD"),
    region: "Africa",
  },
  {
    code: "SR",
    name: "Suriname",
    flag: "🇸🇷",
    flagImageUrl: getFlagImageUrl("SR"),
    region: "Americas",
  },
  {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    flagImageUrl: getFlagImageUrl("SE"),
    region: "Europe",
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    flagImageUrl: getFlagImageUrl("CH"),
    region: "Europe",
  },
  {
    code: "SY",
    name: "Syria",
    flag: "🇸🇾",
    flagImageUrl: getFlagImageUrl("SY"),
    region: "Asia",
  },
  {
    code: "TW",
    name: "Taiwan",
    flag: "🇹🇼",
    flagImageUrl: getFlagImageUrl("TW"),
    region: "Asia",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    flag: "🇹🇯",
    flagImageUrl: getFlagImageUrl("TJ"),
    region: "Asia",
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    flagImageUrl: getFlagImageUrl("TZ"),
    region: "Africa",
  },
  {
    code: "TH",
    name: "Thailand",
    flag: "🇹🇭",
    flagImageUrl: getFlagImageUrl("TH"),
    region: "Asia",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    flag: "🇹🇱",
    flagImageUrl: getFlagImageUrl("TL"),
    region: "Asia",
  },
  {
    code: "TG",
    name: "Togo",
    flag: "🇹🇬",
    flagImageUrl: getFlagImageUrl("TG"),
    region: "Africa",
  },
  {
    code: "TO",
    name: "Tonga",
    flag: "🇹🇴",
    flagImageUrl: getFlagImageUrl("TO"),
    region: "Oceania",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    flagImageUrl: getFlagImageUrl("TT"),
    region: "Americas",
  },
  {
    code: "TN",
    name: "Tunisia",
    flag: "🇹🇳",
    flagImageUrl: getFlagImageUrl("TN"),
    region: "Africa",
  },
  {
    code: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    flagImageUrl: getFlagImageUrl("TR"),
    region: "Asia",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    flag: "🇹🇲",
    flagImageUrl: getFlagImageUrl("TM"),
    region: "Asia",
  },
  {
    code: "TV",
    name: "Tuvalu",
    flag: "🇹🇻",
    flagImageUrl: getFlagImageUrl("TV"),
    region: "Oceania",
  },
  {
    code: "UG",
    name: "Uganda",
    flag: "🇺🇬",
    flagImageUrl: getFlagImageUrl("UG"),
    region: "Africa",
  },
  {
    code: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
    flagImageUrl: getFlagImageUrl("UA"),
    region: "Europe",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    flagImageUrl: getFlagImageUrl("AE"),
    region: "Asia",
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    flagImageUrl: getFlagImageUrl("GB"),
    region: "Europe",
  },
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    flagImageUrl: getFlagImageUrl("US"),
    region: "Americas",
  },
  {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    flagImageUrl: getFlagImageUrl("UY"),
    region: "Americas",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    flag: "🇺🇿",
    flagImageUrl: getFlagImageUrl("UZ"),
    region: "Asia",
  },
  {
    code: "VU",
    name: "Vanuatu",
    flag: "🇻🇺",
    flagImageUrl: getFlagImageUrl("VU"),
    region: "Oceania",
  },
  {
    code: "VA",
    name: "Vatican City",
    flag: "🇻🇦",
    flagImageUrl: getFlagImageUrl("VA"),
    region: "Europe",
  },
  {
    code: "VE",
    name: "Venezuela",
    flag: "🇻🇪",
    flagImageUrl: getFlagImageUrl("VE"),
    region: "Americas",
  },
  {
    code: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
    flagImageUrl: getFlagImageUrl("VN"),
    region: "Asia",
  },
  {
    code: "YE",
    name: "Yemen",
    flag: "🇾🇪",
    flagImageUrl: getFlagImageUrl("YE"),
    region: "Asia",
  },
  {
    code: "ZM",
    name: "Zambia",
    flag: "🇿🇲",
    flagImageUrl: getFlagImageUrl("ZM"),
    region: "Africa",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    flag: "🇿🇼",
    flagImageUrl: getFlagImageUrl("ZW"),
    region: "Africa",
  },
];

/**
 * Get countries as options for select components
 */
export const getCountryOptions = (): CountryOption[] => {
  return COUNTRIES.map((country) => ({
    value: country.code,
    label: country.name,
    code: country.code,
    flag: country.flag,
    flagImageUrl: country.flagImageUrl,
    region: country.region,
  }));
};

/**
 * Get country by code
 */
export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find((country) => country.code === code);
};

/**
 * Get country by name
 */
export const getCountryByName = (name: string): Country | undefined => {
  return COUNTRIES.find(
    (country) => country.name.toLowerCase() === name.toLowerCase()
  );
};

/**
 * Search countries by name or code
 */
export const searchCountries = (query: string): Country[] => {
  const lowercaseQuery = query.toLowerCase();
  return COUNTRIES.filter(
    (country) =>
      country.name.toLowerCase().includes(lowercaseQuery) ||
      country.code.toLowerCase().includes(lowercaseQuery)
  );
};

/**
 * Get countries by region
 */
export const getCountriesByRegion = (region: string): Country[] => {
  return COUNTRIES.filter((country) => country.region === region);
};

/**
 * Get all unique regions
 */
export const getRegions = (): string[] => {
  const regions = new Set(COUNTRIES.map((country) => country.region));
  return Array.from(regions).sort();
};
