export const ROUTES = {
	home: "/",
	login: "/login",
	signup: "/signup",
	broker_signup_success: "/broker-signup-success",
	forgot_password: "/forgot-password",
	reset_password: "/reset-password",
	trustAndSecurity: "/trust-and-security",
	terms: "/terms-and-service",
	policy: "/policy",
	agents: "/agents",
	properties: "/properties",
	expenses: "/expenses",
	inventory: "/inventory",
	renovations: "/renovations",
	documents: "/documents",
	settings: "/settings",
	profile: "/profile",
	bin: "/bin",
};
