import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import App from "./app";
import "react-activity/dist/library.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "UserCanDo",
	description: "Generated by create next app",
	openGraph: {
		images: ["/ucd_logo.png"],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<App>{children}</App>
			</body>
		</html>
	);
}
