export type UserRole =
  | "super_admin"
  | "admin"
  | "user"
  | "owner"
  | "sales_manager"
  | "vendor_sales_agent"
  | "kola_sales_agent"
  | "customer"
  | "sales_staff"
  | "supply_chain_manager"
  | "supply_chain_supervisor"
  | "warehouse_staff"
  | "finance_associate"
  | "finance_admin"
  | "business_analyst"
  | "content_editor"
  | "operations_coordinator";

export type UseCase = "vendor" | "buyer" | "agent" | "both";

export const USE_CASES = {
  VENDOR: "vendor",
  BUYER: "buyer",
  AGENT: "agent",
  BOTH: "both",
} as const;

export const USER_ROLES = {
  // Management
  OWNER: "owner",
  SUPER_ADMIN: "super_admin",

  // Sales
  SALES_MANAGER: "sales_manager",
  VENDOR_SALES_AGENT: "vendor_sales_agent",
  KOLA_SALES_AGENT: "kola_sales_agent",
  CUSTOMER: "customer",
  SALES_STAFF: "sales_staff",

  // Supply Chain
  SUPPLY_CHAIN_MANAGER: "supply_chain_manager",
  SUPPLY_CHAIN_SUPERVISOR: "supply_chain_supervisor",
  WAREHOUSE_STAFF: "warehouse_staff",

  // Finance
  FINANCE_ASSOCIATE: "finance_associate",
  FINANCE_ADMIN: "finance_admin",
  BUSINESS_ANALYST: "business_analyst",

  // Operations
  CONTENT_EDITOR: "content_editor",
  OPERATIONS_COORDINATOR: "operations_coordinator",

  // Default roles
  USER: "user",
} as const;

const MANAGEMENT: UserRole[] = [USER_ROLES.OWNER, USER_ROLES.SUPER_ADMIN];

const SALES_TEAM: UserRole[] = [
  USER_ROLES.SALES_MANAGER,
  USER_ROLES.VENDOR_SALES_AGENT,
  // USER_ROLES.KOLA_SALES_AGENT,
  USER_ROLES.SALES_STAFF,
];

const SUPPLY_CHAIN: UserRole[] = [
  USER_ROLES.SUPPLY_CHAIN_MANAGER,
  USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
  USER_ROLES.WAREHOUSE_STAFF,
];

const FINANCE: UserRole[] = [
  USER_ROLES.FINANCE_ASSOCIATE,
  USER_ROLES.FINANCE_ADMIN,
  USER_ROLES.BUSINESS_ANALYST,
];

const OPERATIONS: UserRole[] = [
  USER_ROLES.CONTENT_EDITOR,
  USER_ROLES.OPERATIONS_COORDINATOR,
];

export const VENDOR_ACCESS: UserRole[] = [
  ...MANAGEMENT,
  ...SALES_TEAM,
  ...SUPPLY_CHAIN,
  ...FINANCE,
  ...OPERATIONS,
];

export const ALL_ROLES: UserRole[] = [
  ...MANAGEMENT,
  ...SALES_TEAM,
  ...SUPPLY_CHAIN,
  ...FINANCE,
  ...OPERATIONS,
  USER_ROLES.USER,
  USER_ROLES.KOLA_SALES_AGENT,
  USER_ROLES.CUSTOMER,
];

export const ROLE_GROUPS = {
  SALES_TEAM,
  SUPPLY_CHAIN,
  FINANCE,
  OPERATIONS,
  MANAGEMENT,
  VENDOR_ACCESS,
  ALL_ROLES,
};

export const ROLE_PERMISSIONS: Record<string, UserRole[]> = {
  // Settings
  UPDATE_PROFILE: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  VIEW_PROFILE: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  CHANGE_PIN: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  CHANGE_PASSWORD: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  // Staff
  CREATE_STAFF: [USER_ROLES.SUPER_ADMIN, USER_ROLES.OWNER],

  VIEW_ALL_STAFF: [USER_ROLES.SUPER_ADMIN, USER_ROLES.OWNER],

  UPDATE_STAFF: [USER_ROLES.SUPER_ADMIN, USER_ROLES.OWNER],

  DELETE_STAFF: [USER_ROLES.SUPER_ADMIN, USER_ROLES.OWNER],

  // Sales
  CREATE_SALE: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.FINANCE_ASSOCIATE,
    USER_ROLES.FINANCE_ADMIN,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_SALES: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    ...ROLE_GROUPS.FINANCE,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_SALE_INFO: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    ...ROLE_GROUPS.FINANCE,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_SALES_COUNT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  UPDATE_SALE: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SALES_STAFF,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  DELETE_SALE: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  DELETE_SALE_PRODUCT: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
  ],

  // Sales POS
  ADD_ABANDONED_CART: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SALES_STAFF,
  ],

  VIEW_ALL_CARTS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SALES_STAFF,
  ],

  VIEW_CART_INFO: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SALES_STAFF,
  ],

  DELETE_CARTS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SALES_STAFF,
  ],

  DELETE_CART: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SALES_STAFF,
  ],

  // Authentication
  LOGOUT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  SIGNUP: [USER_ROLES.OWNER],

  VERIFY_OTP: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  CREATE_PROFILE: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.VENDOR_SALES_AGENT,
  ],

  LOGIN: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  // Forgot Password
  REQUEST_FORGOT_PASSWORD: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  RESET_PASSWORD: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  // Business
  CREATE_BUSINESS: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    USER_ROLES.FINANCE_ASSOCIATE,
    USER_ROLES.FINANCE_ADMIN,
  ],

  VIEW_BUSINESS_INFO: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  VIEW_BUSINESS_COUNT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    ...ROLE_GROUPS.FINANCE,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  UPDATE_BUSINESS: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    USER_ROLES.FINANCE_ASSOCIATE,
    USER_ROLES.FINANCE_ADMIN,
    ...ROLE_GROUPS.OPERATIONS,
  ],

  DELETE_BUSINESS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.VENDOR_SALES_AGENT,
  ],

  // Purchase Orders
  CREATE_PURCHASE_ORDER: [
    ...ROLE_GROUPS.MANAGEMENT,
    // USER_ROLES.SUPER_ADMIN,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.FINANCE_ASSOCIATE,
    USER_ROLES.FINANCE_ADMIN,
  ],

  VIEW_ALL_PURCHASE_ORDERS: [
    ...ROLE_GROUPS.MANAGEMENT,
    // USER_ROLES.SUPER_ADMIN,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    ...ROLE_GROUPS.FINANCE,
  ],

  VIEW_PURCHASE_ORDER: [
    ...ROLE_GROUPS.MANAGEMENT,
    // USER_ROLES.SUPER_ADMIN,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    ...ROLE_GROUPS.FINANCE,
  ],

  UPDATE_PURCHASE_ORDER: [
    ...ROLE_GROUPS.MANAGEMENT,
    // USER_ROLES.SUPER_ADMIN,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.FINANCE_ASSOCIATE,
    USER_ROLES.FINANCE_ADMIN,
  ],

  DELETE_PURCHASE_ORDER: [
    ...ROLE_GROUPS.MANAGEMENT,
    // USER_ROLES.SUPER_ADMIN,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.FINANCE_ASSOCIATE,
    USER_ROLES.FINANCE_ADMIN,
  ],

  // Teams
  CREATE_TEAM: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_TEAMS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_TEAM: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  DELETE_TEAM: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  UPDATE_TEAM: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  // Suppliers
  CREATE_SUPPLIER: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
  ],

  VIEW_SUPPLIER: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.BUSINESS_ANALYST,
  ],

  VIEW_ALL_SUPPLIERS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
    USER_ROLES.BUSINESS_ANALYST,
  ],

  DELETE_SUPPLIER: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
  ],

  // Products
  CREATE_PRODUCT: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
  ],

  VIEW_ALL_PRODUCTS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_PRODUCT_BY_ID: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  UPDATE_PRODUCT: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    ...ROLE_GROUPS.SUPPLY_CHAIN,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  DELETE_PRODUCT: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_MANAGER,
    USER_ROLES.SUPPLY_CHAIN_SUPERVISOR,
  ],

  // Sales Agents
  CREATE_SALES_AGENT: [...ROLE_GROUPS.MANAGEMENT, ...ROLE_GROUPS.SALES_TEAM],

  VIEW_ALL_SALES_AGENTS: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
    USER_ROLES.SUPER_ADMIN,
  ],

  VIEW_SALES_AGENT_INFO: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
    USER_ROLES.SUPER_ADMIN,
  ],

  UPDATE_SALES_AGENT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
    USER_ROLES.SUPER_ADMIN,
  ],

  DELETE_SALES_AGENT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.SUPER_ADMIN,
  ],

  // Request Agent
  CREATE_AGENT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_ALL_AGENTS: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_AGENT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  DELETE_AGENT: [...ROLE_GROUPS.MANAGEMENT, ...ROLE_GROUPS.SALES_TEAM],

  UPDATE_AGENT: [
    ...ROLE_GROUPS.MANAGEMENT,
    ...ROLE_GROUPS.SALES_TEAM,
    USER_ROLES.OPERATIONS_COORDINATOR,
  ],

  VIEW_STATUS: [...ROLE_GROUPS.MANAGEMENT, ...ROLE_GROUPS.SALES_TEAM],

  VIEW_STATUS_HISTORY: [...ROLE_GROUPS.MANAGEMENT, ...ROLE_GROUPS.SALES_TEAM],

  // Customers
  CREATE_CUSTOMER: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.SUPER_ADMIN,
    USER_ROLES.VENDOR_SALES_AGENT,
  ],

  VIEW_ALL_CUSTOMERS: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.VENDOR_SALES_AGENT,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
    USER_ROLES.SUPER_ADMIN,
  ],

  VIEW_CUSTOMER_INFO: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.VENDOR_SALES_AGENT,
    USER_ROLES.BUSINESS_ANALYST,
    USER_ROLES.OPERATIONS_COORDINATOR,
    USER_ROLES.SUPER_ADMIN,
  ],

  UPDATE_CUSTOMER: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.VENDOR_SALES_AGENT,
    USER_ROLES.SUPER_ADMIN,
  ],

  DELETE_CUSTOMER: [
    ...ROLE_GROUPS.MANAGEMENT,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.VENDOR_SALES_AGENT,
    USER_ROLES.SUPER_ADMIN,
  ],

  CREATE_BRANDS: [USER_ROLES.SUPER_ADMIN],

  CREATE_CATEGORY: [USER_ROLES.SUPER_ADMIN],

  // Vendor Access
  VENDOR_ACCESS: [...ROLE_GROUPS.VENDOR_ACCESS],
} as const;
