export const sellingAgentData = [
  { agent_name: "Kwame Asante", sales: 120, sales_value: 45000.25 },
  { agent_name: "Akosua Mensah", sales: 98, sales_value: 38900.75 },
  { agent_name: "Kofi Boateng", sales: 87, sales_value: 32000.5 },
  { agent_name: "Ama Ofori", sales: 110, sales_value: 41000.0 },
  { agent_name: "Yaw Owusu", sales: 75, sales_value: 29000.3 },
  { agent_name: "Efua Addo", sales: 101, sales_value: 36500.85 },
  { agent_name: "Kojo Antwi", sales: 88, sales_value: 31000.2 },
  { agent_name: "Abena Serwaa", sales: 95, sales_value: 37800.4 },
  { agent_name: "Kwesi Appiah", sales: 65, sales_value: 25000.9 },
  { agent_name: "Nana Akuffo", sales: 50, sales_value: 19500.0 },
  { agent_name: "Cynthia Owusu", sales: 112, sales_value: 46800.5 },
  { agent_name: "Samuel Adu", sales: 89, sales_value: 33400.2 },
  { agent_name: "Grace Agyemang", sales: 93, sales_value: 37000.8 },
  { agent_name: "John Mensah", sales: 76, sales_value: 29900.1 },
  { agent_name: "Beatrice Amankwah", sales: 120, sales_value: 49500.9 },
  { agent_name: "Daniel Frimpong", sales: 65, sales_value: 25500.0 },
  { agent_name: "Dorcas Kyei", sales: 102, sales_value: 37800.5 },
  { agent_name: "Josephine Osei", sales: 84, sales_value: 31900.4 },
  { agent_name: "Benjamin Annan", sales: 97, sales_value: 38950.7 },
  { agent_name: "Isaac Tetteh", sales: 81, sales_value: 30700.3 },
  { agent_name: "Martha Aidoo", sales: 75, sales_value: 29200.2 },
  { agent_name: "Kofi Anokye", sales: 69, sales_value: 26400.6 },
  { agent_name: "Selina Owusu", sales: 96, sales_value: 38250.1 },
  { agent_name: "Abigail Oteng", sales: 77, sales_value: 30000.4 },
  { agent_name: "Felix Opoku", sales: 91, sales_value: 36000.0 },
  { agent_name: "Kwame Asante", sales: 120, sales_value: 45000.25 },
  { agent_name: "Akosua Mensah", sales: 98, sales_value: 38900.75 },
  { agent_name: "Kofi Boateng", sales: 87, sales_value: 32000.5 },
  { agent_name: "Ama Ofori", sales: 110, sales_value: 41000.0 },
  { agent_name: "Yaw Owusu", sales: 75, sales_value: 29000.3 },
  { agent_name: "Efua Addo", sales: 101, sales_value: 36500.85 },
  { agent_name: "Kojo Antwi", sales: 88, sales_value: 31000.2 },
  { agent_name: "Abena Serwaa", sales: 95, sales_value: 37800.4 },
  { agent_name: "Kwesi Appiah", sales: 65, sales_value: 25000.9 },
  { agent_name: "Nana Akuffo", sales: 50, sales_value: 19500.0 },
  { agent_name: "Cynthia Owusu", sales: 112, sales_value: 46800.5 },
  { agent_name: "Samuel Adu", sales: 89, sales_value: 33400.2 },
  { agent_name: "Grace Agyemang", sales: 93, sales_value: 37000.8 },
  { agent_name: "John Mensah", sales: 76, sales_value: 29900.1 },
  { agent_name: "Beatrice Amankwah", sales: 120, sales_value: 49500.9 },
  { agent_name: "Daniel Frimpong", sales: 65, sales_value: 25500.0 },
  { agent_name: "Dorcas Kyei", sales: 102, sales_value: 37800.5 },
  { agent_name: "Josephine Osei", sales: 84, sales_value: 31900.4 },
  { agent_name: "Benjamin Annan", sales: 97, sales_value: 38950.7 },
  { agent_name: "Isaac Tetteh", sales: 81, sales_value: 30700.3 },
  { agent_name: "Martha Aidoo", sales: 75, sales_value: 29200.2 },
  { agent_name: "Kofi Anokye", sales: 69, sales_value: 26400.6 },
  { agent_name: "Selina Owusu", sales: 96, sales_value: 38250.1 },
  { agent_name: "Abigail Oteng", sales: 77, sales_value: 30000.4 },
  { agent_name: "Felix Opoku", sales: 91, sales_value: 36000.0 },
];

const data = [
  {
    date: "Jul 8, 2023 5:03PM",
    customer: "Racy Ventures",
    agent: "Raymond Amoah",
    product: 0,
    total_due: "4.17",
    sale_type: "Credit sale",
    status: "Owing",
    top_credit_score: "10",
  },
  {
    date: "Jul 8, 2023 5:03PM",
    customer: "Racy Ventures",
    agent: "Raymond Amoah",
    product: 0,
    total_due: "4.17",
    sale_type: "Credit sale",
    status: "Owing",
    top_credit_score: "20",
  },
  {
    date: "Jul 8, 2023 5:03PM",
    customer: "Racy Ventures",
    agent: "Raymond Amoah",
    product: 0,
    total_due: "4.17",
    sale_type: "Cash sale",
    status: "Paid",
    top_credit_score: "45",
  },
  {
    date: "Jul 8, 2023 5:03PM",
    customer: "Racy Ventures",
    agent: "Raymond Amoah",
    product: 0,
    total_due: "4.17",
    sale_type: "Cash sale",
    status: "Paid",
    top_credit_score: "45",
  },
];

const moreData = Array.from({ length: 19 }, (_, i) => ({
  date: "Jul 8, 2023 5:03PM",
  customer: "Racy Ventures",
  agent: "Raymond Amoah",
  product: 0,
  total_due: "4.17",
  sale_type: i % 2 === 0 ? "Credit sale" : "Cash sale",
  status: i % 2 === 0 ? "Owing" : "Paid",
  top_credit_score: (10 + i * 5).toString(),
}));

export const topSalesData = [...data, ...moreData];

export const topCreditData = Array.from({ length: 27 }, (_, index) => ({
  date: `Jul 8, 2023 5:03PM`,
  customer: `Customer ${index + 1}`,
  agent: `Agent ${index + 1}`,
  last_amount_paid: index % 3 === 0 ? 0 : (Math.random() * 50).toFixed(2),
  total_credit: "GHS 4.17",
  outstanding: "GHS 3.17",
}));

export const salesSummary = [
  {
    period: "Jan 2023 - Feb 2023",
    number_of_sales: 150,
    product_sold: "Solar Panels",
    total_value: "GHS 750",
  },
  {
    period: "Mar 2023 - Apr 2023",
    number_of_sales: 180,
    product_sold: "Inverters",
    total_value: "GHS 900",
  },
  {
    period: "May 2023 - Jun 2023",
    number_of_sales: 210,
    product_sold: "Solar Batteries",
    total_value: "GHS 1,050",
  },
  {
    period: "Jul 2023 - Aug 2023",
    number_of_sales: 300,
    product_sold: "Solar Lights",
    total_value: "GHS 1,500",
  },
  {
    period: "Sep 2023 - Oct 2023",
    number_of_sales: 250,
    product_sold: "Solar Water Heaters",
    total_value: "GHS 1,250",
  },
  {
    period: "Nov 2023 - Dec 2023",
    number_of_sales: 400,
    product_sold: "Solar Panels",
    total_value: "GHS 2,000",
  },
  {
    period: "Jan 2024 - Feb 2024",
    number_of_sales: 320,
    product_sold: "Inverters",
    total_value: "GHS 1,600",
  },
  {
    period: "Mar 2024 - Apr 2024",
    number_of_sales: 280,
    product_sold: "Solar Batteries",
    total_value: "GHS 1,400",
  },
  {
    period: "May 2024 - Jun 2024",
    number_of_sales: 370,
    product_sold: "Solar Lights",
    total_value: "GHS 1,850",
  },
  {
    period: "Jul 2024 - Aug 2024",
    number_of_sales: 450,
    product_sold: "Solar Water Heaters",
    total_value: "GHS 2,250",
  },
  {
    period: "Sep 2024 - Oct 2024",
    number_of_sales: 220,
    product_sold: "Solar Panels",
    total_value: "GHS 1,100",
  },
  {
    period: "Nov 2024 - Dec 2024",
    number_of_sales: 340,
    product_sold: "Inverters",
    total_value: "GHS 1,700",
  },
  {
    period: "Jan 2025 - Feb 2025",
    number_of_sales: 260,
    product_sold: "Solar Batteries",
    total_value: "GHS 1,300",
  },
  {
    period: "Mar 2025 - Apr 2025",
    number_of_sales: 390,
    product_sold: "Solar Lights",
    total_value: "GHS 1,950",
  },
  {
    period: "May 2025 - Jun 2025",
    number_of_sales: 410,
    product_sold: "Solar Water Heaters",
    total_value: "GHS 2,050",
  },
  {
    period: "Jul 2025 - Aug 2025",
    number_of_sales: 360,
    product_sold: "Solar Panels",
    total_value: "GHS 1,800",
  },
  {
    period: "Sep 2025 - Oct 2025",
    number_of_sales: 300,
    product_sold: "Inverters",
    total_value: "GHS 1,500",
  },
  {
    period: "Nov 2025 - Dec 2025",
    number_of_sales: 280,
    product_sold: "Solar Batteries",
    total_value: "GHS 1,400",
  },
  {
    period: "Jan 2026 - Feb 2026",
    number_of_sales: 290,
    product_sold: "Solar Lights",
    total_value: "GHS 1,450",
  },
  {
    period: "Mar 2026 - Apr 2026",
    number_of_sales: 350,
    product_sold: "Solar Water Heaters",
    total_value: "GHS 1,750",
  },
  {
    period: "May 2026 - Jun 2026",
    number_of_sales: 330,
    product_sold: "Solar Panels",
    total_value: "GHS 1,650",
  },
  {
    period: "Jul 2026 - Aug 2026",
    number_of_sales: 240,
    product_sold: "Inverters",
    total_value: "GHS 1,200",
  },
  {
    period: "Sep 2026 - Oct 2026",
    number_of_sales: 400,
    product_sold: "Solar Batteries",
    total_value: "GHS 2,000",
  },
];

export const supplierSalesData = [
  {
    supplier_name: "SolarTech Supplies",
    total_sales_value: "GHS 25,000",
    sales_receipts: 120,
    product_ordered: 450,
    unique_product: "Solar Panels",
    most_frequently_sold_products: "Solar Panels",
  },
  {
    supplier_name: "BrightFuture Energy",
    total_sales_value: "GHS 18,500",
    sales_receipts: 95,
    product_ordered: 360,
    unique_product: "Inverters",
    most_frequently_sold_products: "Inverters",
  },
  {
    supplier_name: "GreenEarth Systems",
    total_sales_value: "GHS 30,200",
    sales_receipts: 140,
    product_ordered: 520,
    unique_product: "Solar Batteries",
    most_frequently_sold_products: "Solar Batteries",
  },
  {
    supplier_name: "EcoLite Power",
    total_sales_value: "GHS 22,800",
    sales_receipts: 110,
    product_ordered: 400,
    unique_product: "Solar Lights",
    most_frequently_sold_products: "Solar Lights",
  },
  {
    supplier_name: "Sunshine Energy Co.",
    total_sales_value: "GHS 19,000",
    sales_receipts: 100,
    product_ordered: 390,
    unique_product: "Solar Water Heaters",
    most_frequently_sold_products: "Solar Water Heaters",
  },
  {
    supplier_name: "NextGen Solar",
    total_sales_value: "GHS 27,400",
    sales_receipts: 130,
    product_ordered: 480,
    unique_product: "Solar Panels",
    most_frequently_sold_products: "Solar Panels",
  },
  {
    supplier_name: "Renewable Tech Solutions",
    total_sales_value: "GHS 20,600",
    sales_receipts: 115,
    product_ordered: 430,
    unique_product: "Solar Batteries",
    most_frequently_sold_products: "Solar Batteries",
  },
  {
    supplier_name: "PowerSmart Distributors",
    total_sales_value: "GHS 15,900",
    sales_receipts: 80,
    product_ordered: 300,
    unique_product: "Inverters",
    most_frequently_sold_products: "Inverters",
  },
  {
    supplier_name: "SustainAbility Systems",
    total_sales_value: "GHS 23,700",
    sales_receipts: 125,
    product_ordered: 410,
    unique_product: "Solar Water Heaters",
    most_frequently_sold_products: "Solar Water Heaters",
  },
  {
    supplier_name: "Bright Horizon Energy",
    total_sales_value: "GHS 26,300",
    sales_receipts: 135,
    product_ordered: 470,
    unique_product: "Solar Lights",
    most_frequently_sold_products: "Solar Lights",
  },
];

export const regionSalesMockData = [
  {
    supplier_name: "SolarTech Supplies",
    sales_between: "Jan 2023 - Dec 2023",
    sales_receipts: 150,
    sales_agent: "Raymond Amoah",
  },
  {
    supplier_name: "BrightFuture Energy",
    sales_between: "Feb 2023 - Nov 2023",
    sales_receipts: 120,
    sales_agent: "Naomi Osei",
  },
  {
    supplier_name: "GreenEarth Systems",
    sales_between: "Mar 2023 - Oct 2023",
    sales_receipts: 175,
    sales_agent: "Kwame Appiah",
  },
  {
    supplier_name: "EcoLite Power",
    sales_between: "Apr 2023 - Sep 2023",
    sales_receipts: 130,
    sales_agent: "Abena Mensah",
  },
  {
    supplier_name: "Sunshine Energy Co.",
    sales_between: "May 2023 - Aug 2023",
    sales_receipts: 145,
    sales_agent: "Michael Owusu",
  },
  {
    supplier_name: "NextGen Solar",
    sales_between: "Jun 2023 - Jul 2023",
    sales_receipts: 110,
    sales_agent: "Sarah Boateng",
  },
  {
    supplier_name: "Renewable Tech Solutions",
    sales_between: "Jan 2024 - Dec 2024",
    sales_receipts: 200,
    sales_agent: "Kojo Dapaah",
  },
  {
    supplier_name: "PowerSmart Distributors",
    sales_between: "Feb 2024 - Nov 2024",
    sales_receipts: 180,
    sales_agent: "Akosua Ansah",
  },
  {
    supplier_name: "SustainAbility Systems",
    sales_between: "Mar 2024 - Oct 2024",
    sales_receipts: 190,
    sales_agent: "Yaw Agyemang",
  },
  {
    supplier_name: "Bright Horizon Energy",
    sales_between: "Apr 2024 - Sep 2024",
    sales_receipts: 160,
    sales_agent: "Nana Adjei",
  },
];

export const allCustomers = [
  {
    id: 1,
    name: "James Wilson",
    businessType: "Wholesaler",
    phone: "+1-555-234-5678",
    country: "United States",
    region: "Northeast",
    city: "Boston",
    address: "127 Commonwealth Avenue",
    location: "Back Bay District",
  },
  {
    id: 2,
    name: "Sarah Chen",
    businessType: "Retailer",
    phone: "+1-555-987-6543",
    country: "Canada",
    region: "Ontario",
    city: "Toronto",
    address: "482 Queen Street West",
    location: "Downtown Core",
  },
  {
    id: 3,
    name: "Michael O'Connor",
    businessType: "Distributor",
    phone: "+353-1-555-0123",
    country: "Ireland",
    region: "Dublin",
    city: "Dublin",
    address: "15 Grafton Street",
    location: "City Centre",
  },
  {
    id: 4,
    name: "Emma Thompson",
    businessType: "Wholesaler",
    phone: "+44-20-5555-0198",
    country: "United Kingdom",
    region: "Greater London",
    city: "London",
    address: "45 Baker Street",
    location: "Marylebone",
  },
  {
    id: 5,
    name: "David Martinez",
    businessType: "Retailer",
    phone: "+1-555-777-9999",
    country: "United States",
    region: "Southwest",
    city: "Austin",
    address: "304 South Congress Avenue",
    location: "Downtown Austin",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    businessType: "Wholesaler",
    phone: "+1-555-444-3333",
    country: "United States",
    region: "West Coast",
    city: "Seattle",
    address: "789 Pike Place",
    location: "Market District",
  },
  {
    id: 7,
    name: "Robert Kim",
    businessType: "Distributor",
    phone: "+82-2-5555-0147",
    country: "South Korea",
    region: "Seoul",
    city: "Seoul",
    address: "123 Gangnam-daero",
    location: "Gangnam District",
  },
  {
    id: 8,
    name: "Sophie Martin",
    businessType: "Retailer",
    phone: "+33-1-5555-0123",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    address: "27 Rue du Commerce",
    location: "15th Arrondissement",
  },
];

export const suppliersData = [
  {
    id: "1",
    name: "Racy Ventures",
    products: ["Product A", "Product B"],
  },
  {
    id: "2",
    name: "lorenz Ventures",
    products: ["Product A", "Product B"],
  },
];

export const allProducts = [
  {
    id: 1,
    productId: "AOB1C008",
    nameOfProduct: "🍰 Coffee Beans, 10kg",
    unitCost: "Ghs 50.00",
    quantity: 65,
    totalCost: `Ghs ${(50 * 65).toFixed(2)}`,
  },
  {
    id: 2,
    productId: "AOB1C009",
    nameOfProduct: "🥛 Fresh Milk, 5L",
    unitCost: "Ghs 30.00",
    quantity: 80,
    totalCost: "Ghs 0.00",
  },
  {
    id: 3,
    productId: "AOB1C010",
    nameOfProduct: "🍞 Whole Wheat Bread, 2 Loaves",
    unitCost: "Ghs 25.00",
    quantity: 2500,
    totalCost: "Ghs 0.00",
  },
  {
    id: 4,
    productId: "AOB1C011",
    nameOfProduct: "🍗 Chicken Drumsticks, 1kg",
    unitCost: "Ghs 70.00",
    quantity: 9000,
    totalCost: "Ghs 0.00",
  },
  {
    id: 5,
    productId: "AOB1C012",
    nameOfProduct: "🥩 Beef Steak, 500g",
    unitCost: "Ghs 90.00",
    quantity: 23,
    totalCost: "Ghs 0.00",
  },
  {
    id: 6,
    productId: "AOB1C013",
    nameOfProduct: "🍎 Red Apples, 1kg",
    unitCost: "Ghs 35.00",
    quantity: 4,
    totalCost: "Ghs 0.00",
  },
  {
    id: 7,
    productId: "AOB1C014",
    nameOfProduct: "🥕 Carrots, 2kg",
    unitCost: "Ghs 20.00",
    quantity: 8000,
    totalCost: "Ghs 0.00",
  },
  {
    id: 8,
    productId: "AOB1C015",
    nameOfProduct: "🍚 Basmati Rice, 5kg",
    unitCost: "Ghs 120.00",
    quantity: 3,
    totalCost: "Ghs 0.00",
  },
  {
    id: 9,
    productId: "AOB1C016",
    nameOfProduct: "🧂 Table Salt, 1kg",
    unitCost: "Ghs 15.00",
    quantity: 0,
    totalCost: "Ghs 0.00",
  },
];

export const invoiceData = [
  {
    id: 1,
    supplier: "Kola Market",
    quantity: "4",
    totalOrderValue: "40,000.00",
    invoiceDate: "2024-02-15",
    file: "invoice_kola_market.pdf",
    unitPrice: "20,000",
    invoiceNumber: "INV-20240215-001",
    totalAmount: "GHS 200.00",
  },
  {
    id: 2,
    supplier: "Tech Store",
    quantity: "5",
    totalOrderValue: "40,000.00",
    unitPrice: "20,000",
    invoiceDate: "2024-03-05",
    file: "invoice_tech_store.pdf",
    invoiceNumber: "INV-20240305-002",
    totalAmount: "GHS 350.00",
  },
];

export const agentRequest = [
  {
    id: 1,
    requestDate: "18/12/24",
    agent: "Racy Ventures",
    productDetail: "Green Tea",
    totalPrice: "GHS 5,500",
    deliveryInfo: "Accra",
    order_status: "Completed",
  },
  {
    id: 2,
    requestDate: "20/12/24",
    agent: "Prime Traders",
    productDetail: "Coffee Beans",
    totalPrice: "GHS 8,200",
    deliveryInfo: "Kumasi",
    order_status: "Pending",
  },
  {
    id: 3,
    requestDate: "22/12/24",
    agent: "Swift Suppliers",
    productDetail: "Milk Powder",
    totalPrice: "GHS 4,750",
    deliveryInfo: "Takoradi",
    order_status: "Completed",
  },
  {
    id: 4,
    requestDate: "25/12/24",
    agent: "Glory Distributors",
    productDetail: "Sugar Cubes",
    totalPrice: "GHS 3,600",
    deliveryInfo: "Tamale",
    order_status: "Placed",
  },
  {
    id: 5,
    requestDate: "27/12/24",
    agent: "Excel Logistics",
    productDetail: "Honey",
    totalPrice: "GHS 6,900",
    deliveryInfo: "Sunyani",
    order_status: "Pending",
  },
  {
    id: 6,
    requestDate: "29/12/24",
    agent: "Top Choice Ltd.",
    productDetail: "Black Tea",
    totalPrice: "GHS 7,300",
    deliveryInfo: "Cape Coast",
    order_status: "Pending",
  },
  {
    id: 7,
    requestDate: "30/12/24",
    agent: "FastTrack Merchants",
    productDetail: "Cocoa Powder",
    totalPrice: "GHS 5,200",
    deliveryInfo: "Ho",
    order_status: "Completed",
  },
  {
    id: 8,
    requestDate: "02/01/25",
    agent: "Evergreen Supply",
    productDetail: "Herbal Tea",
    totalPrice: "GHS 6,400",
    deliveryInfo: "Bolgatanga",
    order_status: "Completed",
  },
  {
    id: 9,
    requestDate: "05/01/25",
    agent: "Premium Goods Ltd.",
    productDetail: "Cashew Nuts",
    totalPrice: "GHS 9,100",
    deliveryInfo: "Wa",
    order_status: "Pending",
  },
];

export const notifications = [
  {
    id: 1,
    date: "19th Dec 2024, 5:50 AM",
    title: "Agent placed request for product",
    content: "Placed a request for 1 product.",
    type: "Agent Request",
    read_status: "unread",
  },
  {
    id: 2,
    date: "20th Dec 2024, 2:15 PM",
    title: "New agent registered",
    content: "A new agent, Prime Traders, has registered.",
    type: "Registration",
    read_status: "read",
  },
  {
    id: 3,
    date: "21st Dec 2024, 9:30 AM",
    title: "Request approved",
    content: "Your request for Green Tea has been approved.",
    type: "Approval",
    read_status: "unread",
  },
  {
    id: 4,
    date: "22nd Dec 2024, 11:45 AM",
    title: "Delivery update",
    content: "Your order is out for delivery.",
    type: "Delivery",
    read_status: "read",
  },
  {
    id: 5,
    date: "23rd Dec 2024, 4:20 PM",
    title: "Payment received",
    content: "Payment of GHS 5,500 has been received.",
    type: "Payment",
    read_status: "unread",
  },
  {
    id: 6,
    date: "24th Dec 2024, 8:05 AM",
    title: "Order canceled",
    content: "Your request for Cocoa Powder was canceled.",
    type: "Cancellation",
    read_status: "read",
  },
  {
    id: 7,
    date: "25th Dec 2024, 10:30 AM",
    title: "New product available",
    content: "Black Tea is now available in stock.",
    type: "Product Update",
    read: "unread",
  },
  {
    id: 8,
    date: "26th Dec 2024, 6:55 PM",
    title: "Account verification completed",
    content: "Your account has been successfully verified.",
    type: "Verification",
    read_status: "read",
  },
  {
    id: 9,
    date: "27th Dec 2024, 3:40 PM",
    title: "Reminder: Pending payment",
    content: "You have a pending payment of GHS 3,600.",
    type: "Reminder",
    read_status: "unread",
  },
];

export const agentProductRequest = [
  {
    id: 1,
    product: "Green Tea",
    quantity: 1,
    unitPrice: "GHS 7.00",
    totalPrice: "GHS 7.00",
  },
  {
    id: 2,
    product: "Buka Rice",
    quantity: 4,
    unitPrice: "GHS 5.00",
    totalPrice: "GHS 5.00",
  },
];

export const orders = [
  {
    id: 1,
    orderDate: "July 8, 2023",
    Type: "Credit",
    customer: "Racy Ventures",
    saleAgent: "Kola Market",
    total: "GHS 4.17",
    dueDate: "16/12/2024",
    order_Status: "Delivered",
  },
  {
    id: 2,
    orderDate: "August 14, 2023",
    Type: "Debit",
    customer: "Green Fields Ltd",
    saleAgent: "Alpha Traders",
    total: "GHS 12.50",
    dueDate: "30/11/2024",
    order_Status: "Out of Delivery",
  },
  {
    id: 3,
    orderDate: "September 2, 2023",
    Type: "Credit",
    customer: "Tech Innovators",
    saleAgent: "Beta Supplies",
    total: "GHS 7.99",
    dueDate: "05/01/2025",
    order_Status: "Declined",
  },
  {
    id: 4,
    orderDate: "October 20, 2023",
    Type: "Debit",
    customer: "Creative Solutions",
    saleAgent: "Gamma Distribution",
    total: "GHS 15.75",
    dueDate: "28/02/2025",
    order_Status: "Approved",
  },
  {
    id: 5,
    orderDate: "November 5, 2023",
    Type: "Credit",
    customer: "Fusion Enterprises",
    saleAgent: "Delta Traders",
    total: "GHS 8.40",
    dueDate: "12/12/2024",
    order_Status: "Delivered",
  },
  {
    id: 6,
    orderDate: "December 1, 2023",
    Type: "Debit",
    customer: "Tech World",
    saleAgent: "Sigma Solutions",
    total: "GHS 18.00",
    dueDate: "20/03/2025",
    order_Status: "Out of Delivery",
  },
];

export const outForDelivery = [
  {
    id: 1,
    orderDate: "July 8, 2023",
    Type: "Credit",
    customer: "Racy Ventures",
    saleAgent: "Kola Market",
    total: "GHS 4.17",
    dueDate: "16/12/2024",
    order_Status: "Out of Delivery",
  },
  {
    id: 2,
    orderDate: "August 14, 2023",
    Type: "Debit",
    customer: "Green Fields Ltd",
    saleAgent: "Alpha Traders",
    total: "GHS 12.50",
    dueDate: "30/11/2024",
    order_Status: "Out of Delivery",
  },
  {
    id: 3,
    orderDate: "September 2, 2023",
    Type: "Credit",
    customer: "Tech Innovators",
    saleAgent: "Beta Supplies",
    total: "GHS 7.99",
    dueDate: "05/01/2025",
    order_Status: "Out of Delivery",
  },
  {
    id: 4,
    orderDate: "October 20, 2023",
    Type: "Debit",
    customer: "Creative Solutions",
    saleAgent: "Gamma Distribution",
    total: "GHS 15.75",
    dueDate: "28/02/2025",
    order_Status: "Out of Delivery",
  },
  {
    id: 5,
    orderDate: "November 5, 2023",
    Type: "Credit",
    customer: "Fusion Enterprises",
    saleAgent: "Delta Traders",
    total: "GHS 8.40",
    dueDate: "12/12/2024",
    order_Status: "Out of Delivery",
  },
  {
    id: 6,
    orderDate: "December 1, 2023",
    Type: "Debit",
    customer: "Tech World",
    saleAgent: "Sigma Solutions",
    total: "GHS 18.00",
    dueDate: "20/03/2025",
    order_Status: "Out of Delivery",
  },
];

export const approvedOrders = [
  {
    id: 1,
    orderDate: "July 8, 2023",
    Type: "Credit",
    customer: "Racy Ventures",
    saleAgent: "Kola Market",
    total: "GHS 4.17",
    dueDate: "16/12/2024",
    order_Status: "Approved",
  },
  {
    id: 2,
    orderDate: "August 14, 2023",
    Type: "Debit",
    customer: "Green Fields Ltd",
    saleAgent: "Alpha Traders",
    total: "GHS 12.50",
    dueDate: "30/11/2024",
    order_Status: "Approved",
  },
  {
    id: 3,
    orderDate: "September 2, 2023",
    Type: "Credit",
    customer: "Tech Innovators",
    saleAgent: "Beta Supplies",
    total: "GHS 7.99",
    dueDate: "05/01/2025",
    order_Status: "Approved",
  },
  {
    id: 4,
    orderDate: "October 20, 2023",
    Type: "Debit",
    customer: "Creative Solutions",
    saleAgent: "Gamma Distribution",
    total: "GHS 15.75",
    dueDate: "28/02/2025",
    order_Status: "Approved",
  },
  {
    id: 5,
    orderDate: "November 5, 2023",
    Type: "Credit",
    customer: "Fusion Enterprises",
    saleAgent: "Delta Traders",
    total: "GHS 8.40",
    dueDate: "12/12/2024",
    order_Status: "Approved",
  },
  {
    id: 6,
    orderDate: "December 1, 2023",
    Type: "Debit",
    customer: "Tech World",
    saleAgent: "Sigma Solutions",
    total: "GHS 18.00",
    dueDate: "20/03/2025",
    order_Status: "Approved",
  },
];

export const deliveredOrders = [
  {
    id: 1,
    orderDate: "July 8, 2023",
    Type: "Credit",
    customer: "Racy Ventures",
    saleAgent: "Kola Market",
    total: "GHS 4.17",
    dueDate: "16/12/2024",
    order_Status: "Delivered",
  },
  {
    id: 2,
    orderDate: "August 14, 2023",
    Type: "Debit",
    customer: "Green Fields Ltd",
    saleAgent: "Alpha Traders",
    total: "GHS 12.50",
    dueDate: "30/11/2024",
    order_Status: "Delivered",
  },
  {
    id: 3,
    orderDate: "September 2, 2023",
    Type: "Credit",
    customer: "Tech Innovators",
    saleAgent: "Beta Supplies",
    total: "GHS 7.99",
    dueDate: "05/01/2025",
    order_Status: "Delivered",
  },
];

export const orderSalesInvoice = [
  {
    id: 1,
    quantity: 1,
    description: "Geisha skin Clnsng Bar Neem &  Basil 180G",
    unitPrice: "GHS 9,618.00",
    totalPrice: "GHS 9,618.00",
  },
  {
    id: 2,
    quantity: 2,
    description: "Organic Lavender Face Toner 250ML",
    unitPrice: "GHS 12,450.00",
    totalPrice: "GHS 24,900.00",
  },
  {
    id: 3,
    quantity: 3,
    description: "Charcoal Detox Facial Mask 100G",
    unitPrice: "GHS 7,275.00",
    totalPrice: "GHS 21,825.00",
  },
  {
    id: 4,
    quantity: 1,
    description: "Vitamin C Brightening Serum 30ML",
    unitPrice: "GHS 15,200.00",
    totalPrice: "GHS 15,200.00",
  },
  {
    id: 5,
    quantity: 4,
    description: "Hydrating Aloe Vera Gel 200G",
    unitPrice: "GHS 5,840.00",
    totalPrice: "GHS 23,360.00",
  },
];

export const salesAgentOwner = [
  {
    id: 1,
    name: "Michael Owusu",
    addedOn: {
      date: "Aug 10, 2023",
      time: "3:45PM",
    },
    phoneNumber: "(+233) 245 678 910",
    role: "Owner",
    latestTarget: {
      amount: "GHS 5,200.00",
      status: "N/A",
    },
    business: "Owusu Enterprise",
  },
  {
    id: 2,
    name: "Ama Serwaa",
    addedOn: {
      date: "Sep 15, 2023",
      time: "11:20AM",
    },
    phoneNumber: "(+233) 209 876 543",
    role: "Owner",
    latestTarget: {
      amount: "GHS 3,750.00",
      status: "N/A",
    },
    business: "Serwaa & Co.",
  },
  {
    id: 3,
    name: "Kwame Asante",
    addedOn: {
      date: "Oct 5, 2023",
      time: "9:10AM",
    },
    phoneNumber: "(+233) 277 456 789",
    role: "Owner",
    latestTarget: {
      amount: "GHS 1,500.00",
      status: "N/A",
    },
    business: "Asante Solutions",
  },
  {
    id: 4,
    name: "Nana Akuffo",
    addedOn: {
      date: "Jul 20, 2023",
      time: "4:00PM",
    },
    phoneNumber: "(+233) 265 345 678",
    role: "Owner",
    latestTarget: {
      amount: "GHS 2,800.00",
      status: "N/A",
    },
    business: "Akuffo Enterprises",
  },
  {
    id: 5,
    name: "Efua Mensah",
    addedOn: {
      date: "Jun 30, 2023",
      time: "2:15PM",
    },
    phoneNumber: "(+233) 243 987 654",
    role: "Owner",
    latestTarget: {
      amount: "GHS 900.00",
      status: "N/A",
    },
    business: "Mensah Trading",
  },
  {
    id: 6,
    name: "Kojo Badu",
    addedOn: {
      date: "May 18, 2023",
      time: "10:30AM",
    },
    phoneNumber: "(+233) 257 654 321",
    role: "Owner",
    latestTarget: {
      amount: "GHS 4,500.00",
      status: "N/A",
    },
    business: "Badu Ventures",
  },
];

export const salesAgentManager = [
  {
    id: 1,
    name: "Michael Owusu",
    addedOn: {
      date: "Aug 10, 2023",
      time: "3:45PM",
    },
    phoneNumber: "(+233) 245 678 910",
    role: "Manager",
    latestTarget: {
      amount: "GHS 5,200.00",
      status: "N/A",
    },
    business: "Owusu Enterprise",
  },
  {
    id: 2,
    name: "Ama Serwaa",
    addedOn: {
      date: "Sep 15, 2023",
      time: "11:20AM",
    },
    phoneNumber: "(+233) 209 876 543",
    role: "Manager",
    latestTarget: {
      amount: "GHS 3,750.00",
      status: "N/A",
    },
    business: "Serwaa & Co.",
  },
  {
    id: 3,
    name: "Kwame Asante",
    addedOn: {
      date: "Oct 5, 2023",
      time: "9:10AM",
    },
    phoneNumber: "(+233) 277 456 789",
    role: "Manager",
    latestTarget: {
      amount: "GHS 1,500.00",
      status: "N/A",
    },
    business: "Asante Solutions",
  },
  {
    id: 4,
    name: "Nana Akuffo",
    addedOn: {
      date: "Jul 20, 2023",
      time: "4:00PM",
    },
    phoneNumber: "(+233) 265 345 678",
    role: "Manager",
    latestTarget: {
      amount: "GHS 2,800.00",
      status: "N/A",
    },
    business: "Akuffo Enterprises",
  },
  {
    id: 5,
    name: "Efua Mensah",
    addedOn: {
      date: "Jun 30, 2023",
      time: "2:15PM",
    },
    phoneNumber: "(+233) 243 987 654",
    role: "Manager",
    latestTarget: {
      amount: "GHS 900.00",
      status: "N/A",
    },
    business: "Mensah Trading",
  },
];

export const salesAgentt = [
  {
    id: 1,
    name: "Michael Owusu",
    addedOn: {
      date: "Aug 10, 2023",
      time: "3:45PM",
    },
    phoneNumber: "(+233) 245 678 910",
    role: "Agent",
    latestTarget: {
      amount: "GHS 5,200.00",
      status: "N/A",
    },
    business: "Owusu Enterprise",
  },
  {
    id: 2,
    name: "Ama Serwaa",
    addedOn: {
      date: "Sep 15, 2023",
      time: "11:20AM",
    },
    phoneNumber: "(+233) 209 876 543",
    role: "Agent",
    latestTarget: {
      amount: "GHS 3,750.00",
      status: "N/A",
    },
    business: "Serwaa & Co.",
  },
  {
    id: 3,
    name: "Kwame Asante",
    addedOn: {
      date: "Oct 5, 2023",
      time: "9:10AM",
    },
    phoneNumber: "(+233) 277 456 789",
    role: "Agent",
    latestTarget: {
      amount: "GHS 1,500.00",
      status: "N/A",
    },
    business: "Asante Solutions",
  },
  {
    id: 4,
    name: "Nana Akuffo",
    addedOn: {
      date: "Jul 20, 2023",
      time: "4:00PM",
    },
    phoneNumber: "(+233) 265 345 678",
    role: "Agent",
    latestTarget: {
      amount: "GHS 2,800.00",
      status: "N/A",
    },
    business: "Akuffo Enterprises",
  },
  {
    id: 5,
    name: "Efua Mensah",
    addedOn: {
      date: "Jun 30, 2023",
      time: "2:15PM",
    },
    phoneNumber: "(+233) 243 987 654",
    role: "Agent",
    latestTarget: {
      amount: "GHS 900.00",
      status: "N/A",
    },
    business: "Mensah Trading",
  },
];

export const agentStock = [
  {
    id: 1,
    supplier: "Michael Owusu",
    agent: "Owusu Enterprise",
    totalStockCollected: "700",
    totalStockValue: "GHS 7,800",
    totalVolumeLeft: "350",
    paymentReceived: "GHS 3,500",
    outstandingBalance: "GHS 4,300",
  },
  {
    id: 2,
    supplier: "Ama Serwaa",
    agent: "Serwaa & Co.",
    totalStockCollected: "1,000",
    totalStockValue: "GHS 10,500",
    totalVolumeLeft: "400",
    paymentReceived: "GHS 6,000",
    outstandingBalance: "GHS 4,500",
  },
  {
    id: 3,
    supplier: "Kwame Asante",
    agent: "Asante Solutions",
    totalStockCollected: "600",
    totalStockValue: "GHS 6,200",
    totalVolumeLeft: "300",
    paymentReceived: "GHS 2,800",
    outstandingBalance: "GHS 3,400",
  },
  {
    id: 4,
    supplier: "Nana Akuffo",
    agent: "Akuffo Enterprises",
    totalStockCollected: "450",
    totalStockValue: "GHS 4,750",
    totalVolumeLeft: "200",
    paymentReceived: "GHS 1,950",
    outstandingBalance: "GHS 2,800",
  },
  {
    id: 5,
    supplier: "Efua Mensah",
    agent: "Mensah Trading",
    totalStockCollected: "850",
    totalStockValue: "GHS 9,000",
    totalVolumeLeft: "500",
    paymentReceived: "GHS 4,500",
    outstandingBalance: "GHS 4,500",
  },
  {
    id: 6,
    supplier: "Kojo Badu",
    agent: "Badu Ventures",
    totalStockCollected: "750",
    totalStockValue: "GHS 8,250",
    totalVolumeLeft: "350",
    paymentReceived: "GHS 3,750",
    outstandingBalance: "GHS 4,500",
  },
  {
    id: 7,
    supplier: "Aisha Alhassan",
    agent: "Alhassan & Sons",
    totalStockCollected: "920",
    totalStockValue: "GHS 10,000",
    totalVolumeLeft: "400",
    paymentReceived: "GHS 5,200",
    outstandingBalance: "GHS 4,800",
  },
  {
    id: 8,
    supplier: "Yaw Opoku",
    agent: "Opoku Distributors",
    totalStockCollected: "1,100",
    totalStockValue: "GHS 12,000",
    totalVolumeLeft: "600",
    paymentReceived: "GHS 6,500",
    outstandingBalance: "GHS 5,500",
  },
];

export const CreditReportData = [
  {
    id: 1,
    date: "17/12/2024",
    customer: "Racy Ventures",
    agent: "Kola Market",
    lastAmountPaid: "GHS 7,800",
    totalCredit: "GHS 10,000",
    outStanding: "GHS 4,500",
    paymentMethod: "Cash",
  },
  {
    id: 2,
    date: "18/12/2024",
    customer: "Alpha Traders",
    agent: "Main Street Agency",
    lastAmountPaid: "GHS 5,000",
    totalCredit: "GHS 12,000",
    outStanding: "GHS 7,000",
    paymentMethod: "Bank Transfer",
  },
  {
    id: 3,
    date: "19/12/2024",
    customer: "Greenfield Supplies",
    agent: "City Hub",
    lastAmountPaid: "GHS 3,200",
    totalCredit: "GHS 9,000",
    outStanding: "GHS 5,800",
    paymentMethod: "Mobile Money",
  },
  {
    id: 4,
    date: "20/12/2024",
    customer: "Best Buy Ghana",
    agent: "Westline Brokers",
    lastAmountPaid: "GHS 6,500",
    totalCredit: "GHS 15,000",
    outStanding: "GHS 8,500",
    paymentMethod: "Card Payment",
  },
  {
    id: 5,
    date: "21/12/2024",
    customer: "Horizon Enterprises",
    agent: "Mega Plaza",
    lastAmountPaid: "GHS 4,000",
    totalCredit: "GHS 8,500",
    outStanding: "GHS 4,500",
    paymentMethod: "Cash",
  },
  {
    id: 6,
    date: "22/12/2024",
    customer: "Oceanic Goods",
    agent: "Sunrise Traders",
    lastAmountPaid: "GHS 7,800",
    totalCredit: "GHS 11,000",
    outStanding: "GHS 3,200",
    paymentMethod: "Bank Transfer",
  },
  {
    id: 7,
    date: "23/12/2024",
    customer: "Dynamic Ventures",
    agent: "Elite Market",
    lastAmountPaid: "GHS 2,500",
    totalCredit: "GHS 6,000",
    outStanding: "GHS 3,500",
    paymentMethod: "Mobile Money",
  },
  {
    id: 8,
    date: "24/12/2024",
    customer: "Goldline Stores",
    agent: "Capital Dealers",
    lastAmountPaid: "GHS 9,000",
    totalCredit: "GHS 13,000",
    outStanding: "GHS 4,000",
    paymentMethod: "Card Payment",
  },
];

export const CreditReportDataBusiness = [
  {
    id: 1,
    date: "17/12/2024",
    customer: "Racy Ventures",
    supplier: "Kola Market",
    totalPaid: "GHS 5,500",
    totalCredit: "GHS 7,800",
    outStanding: "GHS 4,500",
  },
  {
    id: 2,
    date: "18/12/2024",
    customer: "Alpha Traders",
    supplier: "Main Street Supplies",
    totalPaid: "GHS 6,200",
    totalCredit: "GHS 9,000",
    outStanding: "GHS 2,800",
  },
  {
    id: 3,
    date: "19/12/2024",
    customer: "Greenfield Supplies",
    supplier: "City Wholesale",
    totalPaid: "GHS 4,000",
    totalCredit: "GHS 10,000",
    outStanding: "GHS 6,000",
  },
  {
    id: 4,
    date: "20/12/2024",
    customer: "Best Buy Ghana",
    supplier: "Westline Distributors",
    totalPaid: "GHS 8,500",
    totalCredit: "GHS 12,000",
    outStanding: "GHS 3,500",
  },
  {
    id: 5,
    date: "21/12/2024",
    customer: "Horizon Enterprises",
    supplier: "Mega Plaza Suppliers",
    totalPaid: "GHS 7,000",
    totalCredit: "GHS 10,500",
    outStanding: "GHS 3,500",
  },
  {
    id: 6,
    date: "22/12/2024",
    customer: "Oceanic Goods",
    supplier: "Sunrise Traders",
    totalPaid: "GHS 9,200",
    totalCredit: "GHS 14,000",
    outStanding: "GHS 4,800",
  },
  {
    id: 7,
    date: "23/12/2024",
    customer: "Dynamic Ventures",
    supplier: "Elite Market Distributors",
    totalPaid: "GHS 5,600",
    totalCredit: "GHS 8,700",
    outStanding: "GHS 3,100",
  },
  {
    id: 8,
    date: "24/12/2024",
    customer: "Goldline Stores",
    supplier: "Capital Dealers Ltd.",
    totalPaid: "GHS 10,000",
    totalCredit: "GHS 15,500",
    outStanding: "GHS 5,500",
  },
];

export const TeamsData = [
  {
    id: 1,
    firstName: "Ayekua",
    lastName: "Ampha",
    email: "Oyekuo23@gmail.com",
    phoneNumber: "+2348174234567",
    business: "Kola Market",
    role: "Owner",
  },
  {
    id: 1,
    firstName: "Melody",
    lastName: "Grace",
    email: "melody23@gmail.com",
    phoneNumber: "+234889201823",
    business: "Kola Market",
    role: "Operations Manager",
  },
];

export const supplierOrders = [
  {
    order_date: "2024-12-12",
    type: "Credit",
    customer: "John Doe",
    sales_agent: "Kola Market",
    total: "GHS 1500.0",
    due_date: "2024-12-16",
    order_status: "Approved",
  },
  {
    order_date: "2024-12-13",
    type: "Cash",
    customer: "Alice Johnson",
    sales_agent: "Kola Market",
    total: "GHS 3200.00",
    due_date: "2024-12-20",
    order_status: "Pending",
  },
  {
    order_date: "2024-12-14",
    type: "Credit",
    customer: "Michael Brown",
    sales_agent: "Kola Market",
    total: "GHS 2800.00",
    due_date: "2024-12-18",
    order_status: "Approved",
  },
  {
    order_date: "2024-12-15",
    type: "Cash",
    customer: "Emma Davis",
    sales_agent: "Kola Market",
    total: "GHS 1500.00",
    due_date: "2024-12-19",
    order_status: "Approved",
  },
  {
    order_date: "2024-12-16",
    type: "Credit",
    customer: "Liam Miller",
    sales_agent: "Kola Market",
    total: "GHS 4500.00",
    due_date: "2024-12-23",
    order_status: "Shipped",
  },
  {
    order_date: "2024-12-17",
    type: "Cash",
    customer: "Sophia Moore",
    sales_agent: "Kola Market",
    total: "GHS 2200.00",
    due_date: "2024-12-22",
    order_status: "Pending",
  },
  {
    order_date: "2024-12-18",
    type: "Credit",
    customer: "Jacob Garcia",
    sales_agent: "Kola Market",
    total: "GHS 3700.00",
    due_date: "2024-12-25",
    order_status: "Approved",
  },
  {
    order_date: "2024-12-19",
    type: "Cash",
    customer: "Charlotte Rodriguez",
    sales_agent: "Kola Market",
    total: "GHS 2400.00",
    due_date: "2024-12-26",
    order_status: "Approved",
  },
  {
    order_date: "2024-12-20",
    type: "Credit",
    customer: "Mason Lee",
    sales_agent: "Kola Market",
    total: "GHS 5300.00",
    due_date: "2024-12-27",
    order_status: "Shipped",
  },
  {
    order_date: "2024-12-21",
    type: "Cash",
    customer: "Amelia Lewis",
    sales_agent: "Kola Market",
    total: "GHS 1800.00",
    due_date: "2024-12-28",
    order_status: "Pending",
  },
  {
    order_date: "2024-12-22",
    type: "Credit",
    customer: "William Young",
    sales_agent: "Kola Market",
    total: "GHS 3000.00",
    due_date: "2024-12-29",
    order_status: "Approved",
  },
  {
    order_date: "2024-12-23",
    type: "Cash",
    customer: "Benjamin King",
    sales_agent: "Kola Market",
    total: "GHS 2200.00",
    due_date: "2024-12-30",
    order_status: "Shipped",
  },
  {
    order_date: "2024-12-24",
    type: "Credit",
    customer: "Daniel Scott",
    sales_agent: "Kola Market",
    total: "GHS 3800.00",
    due_date: "2024-12-31",
    order_status: "Pending",
  },
  {
    order_date: "2024-12-25",
    type: "Cash",
    customer: "Evelyn Wright",
    sales_agent: "Kola Market",
    total: "GHS 1600.00",
    due_date: "2025-01-01",
    order_status: "Approved",
  },
];

export const suppliers = [
  {
    added_on: "2024-01-10T12:30:00Z",
    business: "Tech Solutions",
    email: "contact@techsolutions.com",
    owner: { phone: "+1234567890" },
    location: "Lagos, Nigeria",
  },
  {
    added_on: "2024-01-11T09:45:00Z",
    business: "Innovative Systems",
    email: "info@innosys.com",
    owner: { phone: "+1987654321" },
    location: "Abuja, Nigeria",
  },
  {
    added_on: "2024-01-12T15:00:00Z",
    business: "Web Creators",
    email: "support@webcreators.com",
    owner: { phone: "+1230987654" },
    location: "Port Harcourt, Nigeria",
  },
  {
    added_on: "2024-01-13T14:25:00Z",
    business: "CodeCrafters",
    email: "contact@codecrafters.com",
    owner: { phone: "+1543216789" },
    location: "Lagos, Nigeria",
  },
  {
    added_on: "2024-01-14T08:30:00Z",
    business: "GreenTech Innovations",
    email: "green@greentech.com",
    owner: { phone: "+1234567800" },
    location: "Abuja, Nigeria",
  },
  {
    added_on: "2024-01-15T11:00:00Z",
    business: "Fast Logistics",
    email: "info@fastlogistics.com",
    owner: { phone: "+1765432109" },
    location: "Kaduna, Nigeria",
  },
  {
    added_on: "2024-01-16T10:15:00Z",
    business: "Future Enterprises",
    email: "future@enterprises.com",
    owner: { phone: "+1245678901" },
    location: "Enugu, Nigeria",
  },
  {
    added_on: "2024-01-17T16:20:00Z",
    business: "TechnoSage",
    email: "contact@technosage.com",
    owner: { phone: "+1456789012" },
    location: "Lagos, Nigeria",
  },
  {
    added_on: "2024-01-18T13:45:00Z",
    business: "DevX Solutions",
    email: "hello@devxsolutions.com",
    owner: { phone: "+1256789032" },
    location: "Port Harcourt, Nigeria",
  },
  {
    added_on: "2024-01-19T17:30:00Z",
    business: "Smart Innovations",
    email: "info@smartinnovations.com",
    owner: { phone: "+1987654329" },
    location: "Abuja, Nigeria",
  },
  {
    added_on: "2024-01-20T12:00:00Z",
    business: "DataWorks",
    email: "contact@dataworks.com",
    owner: { phone: "+1276543210" },
    location: "Kaduna, Nigeria",
  },
  {
    added_on: "2024-01-21T14:10:00Z",
    business: "Creative Minds",
    email: "creative@creativeminds.com",
    owner: { phone: "+1398765432" },
    location: "Enugu, Nigeria",
  },
  {
    added_on: "2024-01-22T09:00:00Z",
    business: "CodeSprint",
    email: "hello@codesprint.com",
    owner: { phone: "+1567894320" },
    location: "Lagos, Nigeria",
  },
  {
    added_on: "2024-01-23T11:25:00Z",
    business: "Byte Tech",
    email: "support@bytech.com",
    owner: { phone: "+1345678902" },
    location: "Port Harcourt, Nigeria",
  },
  {
    added_on: "2024-01-24T16:35:00Z",
    business: "CloudSavvy",
    email: "cloud@cloudsavvy.com",
    owner: { phone: "+1457894321" },
    location: "Abuja, Nigeria",
  },
  {
    added_on: "2024-01-25T10:45:00Z",
    business: "NextGen Systems",
    email: "nextgen@systems.com",
    owner: { phone: "+1345678912" },
    location: "Lagos, Nigeria",
  },
];

export const inventoryData = [
  {
    id: 1,
    productName: "Green Tea, 5kg",
    businessName: "Racy Ventures",
    category: "Snacks",
    brand: "Unilever",
    inStock: 10,
    wholesale: 225.96,
    retail: 0.0,
    lastModified: "2 Days Ago",
  },
  {
    id: 2,
    productName: "Coffee Beans, 10kg",
    businessName: "Racy Ventures",
    category: "Beverages",
    brand: "Lipton",
    inStock: 15,
    wholesale: 150.5,
    retail: 180.0,
    lastModified: "3 Days Ago",
  },
  {
    id: 3,
    productName: "Milk Powder, 2kg",
    businessName: "Dairy World",
    category: "Dairy",
    brand: "Nestle",
    inStock: 30,
    wholesale: 95.75,
    retail: 110.0,
    lastModified: "1 Week Ago",
  },
  {
    id: 4,
    productName: "Tomato Ketchup, 1L",
    businessName: "Spice Hub",
    category: "Condiments",
    brand: "Heinz",
    inStock: 50,
    wholesale: 45.99,
    retail: 50.0,
    lastModified: "5 Days Ago",
  },
  {
    id: 5,
    productName: "Wheat Bread, 500g",
    businessName: "Healthy Bakes",
    category: "Bakery",
    brand: "Sunshine Bakers",
    inStock: 20,
    wholesale: 30.0,
    retail: 35.5,
    lastModified: "Yesterday",
  },
  {
    id: 6,
    productName: "Olive Oil, 750ml",
    businessName: "Racy Ventures",
    category: "Oils & Fats",
    brand: "Bertolli",
    inStock: 25,
    wholesale: 120.99,
    retail: 135.0,
    lastModified: "4 Days Ago",
  },
  {
    id: 7,
    productName: "Instant Noodles, 75g (5 Packs)",
    businessName: "Fast Foods Ltd.",
    category: "Convenience Foods",
    brand: "Indomie",
    inStock: 40,
    wholesale: 10.99,
    retail: 12.5,
    lastModified: "2 Days Ago",
  },
  {
    id: 8,
    nameOfProduct: "Canned Tuna, 250g",
    businessName: "Ocean Fresh",
    category: "Seafood",
    brand: "John West",
    inStock: 18,
    wholesale: 60.0,
    retail: 68.0,
    lastModified: "3 Weeks Ago",
  },
];

export const inventoryLogs = [
  {
    Date: "Dec 11, 2024 04:32am",
    user: "Marie Reine",
    Log: "Uploaded File",
    Action: "Uploaded File",
  },
  {
    Date: "Dec 12, 2024 10:15am",
    user: "John Doe",
    Log: "Edited Document",
    Action: "Updated File",
  },
  {
    Date: "Dec 13, 2024 02:45pm",
    user: "Alice Johnson",
    Log: "Deleted Record",
    Action: "Removed Entry",
  },
  {
    Date: "Dec 14, 2024 06:20pm",
    user: "Bob Smith",
    Log: "Added New Item",
    Action: "Created Entry",
  },
  {
    Date: "Dec 15, 2024 08:55am",
    user: "Sophia Lee",
    Log: "Updated Settings",
    Action: "Changed Preferences",
  },
  {
    Date: "Dec 16, 2024 01:10pm",
    user: "Daniel Kim",
    Log: "Downloaded Report",
    Action: "Exported File",
  },
];

export const purchaseOrders = [
  {
    id: 1,
    added_on: "2023-07-08T10:15:00Z",
    products: "Green Tea, Spaghetti",
    supplier: "Racy Ventures",
    amount: "GHS 20",
    paymentType: "Cash",
    status: "Delivered",
  },
  {
    id: 2,
    added_on: "2023-08-15T14:45:00Z",
    products: "Rice, Beans, Palm Oil",
    supplier: "Golden Foods Ltd",
    amount: "GHS 45",
    paymentType: "Credit (One-Time)",
    status: "Accepted",
  },
  {
    id: 3,
    added_on: "2023-09-03T09:20:00Z",
    products: "Milk, Sugar, Cocoa Powder",
    supplier: "Dairy Best Supplies",
    amount: "GHS 30",
    paymentType: "Cash",
    status: "Delivered",
  },
  {
    id: 4,
    added_on: "2023-10-12T16:10:00Z",
    products: "Tomato Paste, Noodles, Seasoning Cubes",
    supplier: "Supermart Wholesale",
    amount: "GHS 20",
    paymentType: "Credit (One-Time)",
    status: "Accepted",
  },
  {
    id: 5,
    added_on: "2023-11-20T11:55:00Z",
    products: "Flour, Yeast, Baking Powder",
    supplier: "Bakers Haven",
    paymentType: "Cash",
    amount: "GHS 15",
    status: "Delivered",
  },
  {
    id: 6,
    added_on: "2023-12-05T13:25:00Z",
    products: "Groundnut Oil, Margarine, Salt",
    supplier: "Fresh Farm Supplies",
    paymentType: "Credit (One-Time)",
    status: "Accepted",
  },
  {
    id: 7,
    addedOn: "2024-01-10T12:30:00Z",
    products: "Eggs, Butter, Cheese",
    supplier: "Dairy Delight",
    paymentType: "Cash",
    status: "Delivered",
  },
  {
    id: 8,
    added_on: "2024-02-18T08:40:00Z",
    products: "Cereal, Oats, Honey",
    supplier: "Healthy Living Stores",
    paymentType: "Credit (One-Time)",
    status: "Accepted",
  },
];

export const salePosCart = [
  {
    id: 1,
    product: "Green Tea",
    quantity: 1,
    unitPrice: "GHS",
    totalPrice: "GHS 0.00",
  },
  {
    unitPrice: "Sub Total",
    totalPrice: "GHS 0.00",
    total: "GHS 0.00",
  },
  {
    unitPrice: "Discount",
    totalPrice: "-GHS 0.00",
    total: "GHS 0.00",
  },
];

export const suppliersTermAllRequest = [
  {
    id: 1,
    requestedDate: "Mar 2, 2024",
    issuedDate: "Mar 8, 2024",
    customer: "John Marcus",
    totalPayable: "GHS200,000.00",
    approvalStatus: "CEO Approved",
    dueDate: "Mar 15, 2024",
    requestType: "New",
    disbursementDate: "Mar 10, 2024",
    approvalDate: "Mar 7, 2024",
  },
  {
    id: 2,
    requestedDate: "Apr 5, 2024",
    issuedDate: "Apr 10, 2024",
    customer: "Sophia Adams",
    totalPayable: "GHS150,000.00",
    approvalStatus: "Under Review",
    dueDate: "Apr 20, 2024",
    requestType: "Renewal",
    disbursementDate: "Apr 12, 2024",
    approvalDate: "Mar 7, 2024",
  },
  {
    id: 3,
    requestedDate: "May 12, 2024",
    issuedDate: "May 18, 2024",
    customer: "Michael Brown",
    totalPayable: "GHS500,000.00",
    approvalStatus: "CEO Approved",
    dueDate: "May 25, 2024",
    requestType: "Upgrade",
    disbursementDate: "May 20, 2024",
    approvalDate: "May 17, 2024",
  },
  {
    id: 4,
    requestedDate: "Jun 8, 2024",
    issuedDate: "Jun 12, 2024",
    customer: "Emily Johnson",
    totalPayable: "GHS320,000.00",
    approvalStatus: "Under Review",
    dueDate: "Jun 30, 2024",
    requestType: "New",
    disbursementDate: "Jun 15, 2024",
    approvalDate: "Mar 7, 2024",
  },
  {
    id: 5,
    requestedDate: "Jul 1, 2024",
    issuedDate: "Jul 5, 2024",
    customer: "David Wilson",
    totalPayable: "GHS780,000.00",
    approvalStatus: "CEO Approved",
    dueDate: "Jul 20, 2024",
    requestType: "Renewal",
    disbursementDate: "Jul 8, 2024",
    approvalDate: "Jul 4, 2024",
  },
  {
    id: 6,
    requestedDate: "Aug 15, 2024",
    issuedDate: "Aug 18, 2024",
    customer: "Jessica Carter",
    totalPayable: "GHS1,200,000.00",
    approvalStatus: "Under Review",
    dueDate: "Sep 1, 2024",
    requestType: "Upgrade",
    disbursementDate: "Aug 22, 2024",
    approvalDate: "Sep 14, 2024",
  },
  {
    id: 7,
    requestedDate: "Sep 10, 2024",
    issuedDate: "Sep 15, 2024",
    customer: "Daniel White",
    totalPayable: "GHS2,500,000.00",
    approvalStatus: "CEO Approved",
    dueDate: "Sep 30, 2024",
    requestType: "New",
    disbursementDate: "Sep 18, 2024",
    approvalDate: "Sep 14, 2024",
  },
];

export const salesLogs = [
  {
    Date: "Dec 11, 2024 04:32am",
    user: "Marie Reine",
    Log: "Uploaded File",
    Action: "Uploaded File",
  },
  {
    Date: "Dec 12, 2024 10:15am",
    user: "John Doe",
    Log: "Edited Document",
    Action: "Updated File",
  },
  {
    Date: "Dec 13, 2024 02:45pm",
    user: "Alice Johnson",
    Log: "Deleted Record",
    Action: "Removed Entry",
  },
  {
    Date: "Dec 14, 2024 06:20pm",
    user: "Bob Smith",
    Log: "Added New Item",
    Action: "Created Entry",
  },
  {
    Date: "Dec 15, 2024 08:55am",
    user: "Sophia Lee",
    Log: "Updated Settings",
    Action: "Changed Preferences",
  },
  {
    Date: "Dec 16, 2024 01:10pm",
    user: "Daniel Kim",
    Log: "Downloaded Report",
    Action: "Exported File",
  },
];

export const shopperCustomers = [
  {
    business_name: "Kwame's Electronics",
    business_phone: "+233 24 123 4567",
    business_location: "12 Oxford Street, Accra, Ghana",
    owner_full_name: "Kwame Mensah",
    owner_phone: "+233 20 987 6543",
    country: "Ghana",
    region: "Greater Accra",
    city: "Accra",
    sales_agent: "Ama Boateng",
    customer_type: "Retail",
  },
  {
    business_name: "Osei Ventures",
    business_phone: "+233 55 234 5678",
    business_location: "45 Kejetia Market, Kumasi, Ghana",
    owner_full_name: "Yaw Osei",
    owner_phone: "+233 50 876 5432",
    country: "Ghana",
    region: "Ashanti",
    city: "Kumasi",
    sales_agent: "Kofi Asante",
    customer_type: "Wholesale",
  },
  {
    business_name: "Afriyie Farms",
    business_phone: "+233 26 345 6789",
    business_location: "20 Cape Coast Road, Cape Coast, Ghana",
    owner_full_name: "Akua Afriyie",
    owner_phone: "+233 27 765 4321",
    country: "Ghana",
    region: "Central",
    city: "Cape Coast",
    sales_agent: "Kojo Appiah",
    customer_type: "Agriculture",
  },
];

export const accountActivity = [
  {
    label: "Gifty Johnson was added to team",
    detail:
      "device information: apple iphone, IP address 192.168.1.1, location: San Francisco, CA",
    image: "https://docs.material-tailwind.com/img/face-2.jpg",
  },
  {
    label: "John Doe updated his profile information",
    detail:
      "John changed his email to john.doe@example.com and updated phone number to +1 (555) 123-4567",
    image: "https://docs.material-tailwind.com/img/face-2.jpg",
  },
  {
    label: "Alice Smith changed her password",
    detail:
      "Password changed successfully from device: Windows PC, IP address 192.168.1.5, location: New York, NY",
    image: "https://docs.material-tailwind.com/img/face-2.jpg",
  },
  {
    label: "David Brown uploaded a new document",
    detail:
      "Document 'ProjectProposal.pdf' uploaded to shared workspace. Size: 2.3MB. Access permissions: Team-wide.",
    image: "https://docs.material-tailwind.com/img/face-2.jpg",
  },
];

export const creditItems = [
  {
    order_ID: "#456-1237",
    status: "pending",
    store_name: "Medino-sobston stores",
    location: "Achimota Golf club, Accra, Ghana",
    due_date: "12th Nov. 2024",
    items: 3,
    amount: 235.09,
  },
  {
    order_ID: "#789-4561",
    status: "completed",
    store_name: "Kofi Mart",
    location: "Osu, Accra, Ghana",
    due_date: "5th Mar. 2024",
    items: 5,
    amount: 499.99,
  },
  {
    order_ID: "#321-7894",
    status: "cancelled",
    store_name: "Kwame’s Electronics",
    location: "Tema Community 1, Ghana",
    due_date: "22nd Feb. 2024",
    items: 2,
    amount: 150.75,
  },
  {
    order_ID: "#654-2589",
    status: "shipped",
    store_name: "SuperMart Express",
    location: "East Legon, Accra, Ghana",
    due_date: "30th Apr. 2024",
    items: 8,
    amount: 785.5,
  },
];

export const creditData = [
  {
    applicationNumber: "12345-797929",
    applicationDate: "Jul 8, 2023 5:03PM",
    name: "Racy Ventures",
    title: "Wholesaler",
    dueDate: "16/2/2024",
    status: "Approved",
  },
  {
    applicationNumber: "23456-882341",
    applicationDate: "Aug 12, 2023 10:45AM",
    name: "Nova Supplies",
    title: "Retailer",
    dueDate: "20/3/2024",
    status: "Approved",
  },
  {
    applicationNumber: "34567-123456",
    applicationDate: "Sep 5, 2023 1:22PM",
    name: "GlideMart Ltd.",
    title: "Distributor",
    dueDate: "10/4/2024",
    status: "Approved",
  },
  {
    applicationNumber: "45678-654321",
    applicationDate: "Oct 17, 2023 4:00PM",
    name: "Freshway Foods",
    title: "Wholesaler",
    dueDate: "5/5/2024",
    status: "Approved",
  },
  {
    applicationNumber: "56789-234567",
    applicationDate: "Nov 3, 2023 9:18AM",
    name: "Urban Traders",
    title: "Retailer",
    dueDate: "15/5/2024",
    status: "Approved",
  },
  {
    applicationNumber: "67890-987654",
    applicationDate: "Dec 21, 2023 11:07AM",
    name: "Prime Deals",
    title: "Supplier",
    dueDate: "25/6/2024",
    status: "Approved",
  },
  {
    applicationNumber: "78901-345678",
    applicationDate: "Jan 10, 2024 2:55PM",
    name: "ValueMart",
    title: "Wholesaler",
    dueDate: "1/7/2024",
    status: "Approved",
  },
  {
    applicationNumber: "89012-876543",
    applicationDate: "Feb 14, 2024 8:30AM",
    name: "EcoBiz Ltd.",
    title: "Retailer",
    dueDate: "10/8/2024",
    status: "Approved",
  },
  {
    applicationNumber: "90123-112233",
    applicationDate: "Mar 6, 2024 3:15PM",
    name: "QuickMart NG",
    title: "Supplier",
    dueDate: "20/9/2024",
    status: "Approved",
  },
];

export const creditPayback = [
  {
    applicationNumber: "12345-797929",
    applicationDate: "Jul 8, 2023 5:03PM",
    purchaseOrderNumber: "2345-797929",
    paymentAmount: "GHS 500",
    balance: "GHS 600",
    PaymentDate: "16/2/2024",
  },
  {
    applicationNumber: "23456-882341",
    applicationDate: "Aug 12, 2023 10:45AM",
    purchaseOrderNumber: "3456-882341",
    paymentAmount: "GHS 800",
    balance: "GHS 200",
    PaymentDate: "20/3/2024",
  },
  {
    applicationNumber: "34567-123456",
    applicationDate: "Sep 5, 2023 1:22PM",
    purchaseOrderNumber: "4567-123456",
    paymentAmount: "GHS 1000",
    balance: "GHS 0",
    PaymentDate: "10/4/2024",
  },
  {
    applicationNumber: "45678-654321",
    applicationDate: "Oct 17, 2023 4:00PM",
    purchaseOrderNumber: "5678-654321",
    paymentAmount: "GHS 300",
    balance: "GHS 700",
    PaymentDate: "5/5/2024",
  },
  {
    applicationNumber: "56789-234567",
    applicationDate: "Nov 3, 2023 9:18AM",
    purchaseOrderNumber: "6789-234567",
    paymentAmount: "GHS 900",
    balance: "GHS 100",
    PaymentDate: "15/5/2024",
  },
  {
    applicationNumber: "67890-987654",
    applicationDate: "Dec 21, 2023 11:07AM",
    purchaseOrderNumber: "7890-987654",
    paymentAmount: "GHS 450",
    balance: "GHS 550",
    PaymentDate: "25/6/2024",
  },
  {
    applicationNumber: "78901-345678",
    applicationDate: "Jan 10, 2024 2:55PM",
    purchaseOrderNumber: "8901-345678",
    paymentAmount: "GHS 600",
    balance: "GHS 400",
    PaymentDate: "1/7/2024",
  },
  {
    applicationNumber: "89012-876543",
    applicationDate: "Feb 14, 2024 8:30AM",
    purchaseOrderNumber: "9012-876543",
    paymentAmount: "GHS 750",
    balance: "GHS 250",
    PaymentDate: "10/8/2024",
  },
  {
    applicationNumber: "90123-112233",
    applicationDate: "Mar 6, 2024 3:15PM",
    purchaseOrderNumber: "0123-112233",
    paymentAmount: "GHS 520",
    balance: "GHS 480",
    PaymentDate: "20/9/2024",
  },
];

export const creditPurchase = [
  {
    applicationNumber: "12345-797929",
    purchaseOrderNumber: "2345-797929",
    supplier: "Racy Ventures",
    totalCredit: "GHS 2,000",
    amountPaid: "GHS 1,000",
    amountDue: "GHS 1,000",
  },
  {
    applicationNumber: "23456-882341",
    purchaseOrderNumber: "3456-882341",
    supplier: "Nova Supplies",
    totalCredit: "GHS 3,500",
    amountPaid: "GHS 2,000",
    amountDue: "GHS 1,500",
  },
  {
    applicationNumber: "34567-123456",
    purchaseOrderNumber: "4567-123456",
    supplier: "GlideMart Ltd.",
    totalCredit: "GHS 4,000",
    amountPaid: "GHS 4,000",
    amountDue: "GHS 0",
  },
  {
    applicationNumber: "45678-654321",
    purchaseOrderNumber: "5678-654321",
    supplier: "Freshway Foods",
    totalCredit: "GHS 1,800",
    amountPaid: "GHS 800",
    amountDue: "GHS 1,000",
  },
  {
    applicationNumber: "56789-234567",
    purchaseOrderNumber: "6789-234567",
    supplier: "Urban Traders",
    totalCredit: "GHS 5,000",
    amountPaid: "GHS 3,000",
    amountDue: "GHS 2,000",
  },
  {
    applicationNumber: "67890-987654",
    purchaseOrderNumber: "7890-987654",
    supplier: "Prime Deals",
    totalCredit: "GHS 2,200",
    amountPaid: "GHS 1,500",
    amountDue: "GHS 700",
  },
  {
    applicationNumber: "78901-345678",
    purchaseOrderNumber: "8901-345678",
    supplier: "ValueMart",
    totalCredit: "GHS 3,000",
    amountPaid: "GHS 1,000",
    amountDue: "GHS 2,000",
  },
  {
    applicationNumber: "89012-876543",
    purchaseOrderNumber: "9012-876543",
    supplier: "EcoBiz Ltd.",
    totalCredit: "GHS 4,500",
    amountPaid: "GHS 3,000",
    amountDue: "GHS 1,500",
  },
  {
    applicationNumber: "90123-112233",
    purchaseOrderNumber: "0123-112233",
    supplier: "QuickMart NG",
    totalCredit: "GHS 2,700",
    amountPaid: "GHS 2,200",
    amountDue: "GHS 500",
  },
];

export const salesHistory = [
  {
    businessName: "Amazing Grace Enterprice",
    date: "March 15, 2024",
  },
  {
    businessName: "Amazing Grace Enterprice",
    date: "March 15, 2024",
  },
];

export const switchTeams = [
  {
    name: "Kola Wholesale Market",
    role: "Sales Agent",
    location: "Accra, Ghana",
  },
  {
    name: "Kola Market Supply Services",
    role: "Sales Agent",
    location: "Kola Market Inc.",
  },
];

export const agentRequestProdut = [
  {
    productName: "Catalina Crunch",
    type: "Butter Sandwich Cookies",
    price: "GHS 109.99",
    pieces: 86,
  },
  {
    productName: "Nature Valley",
    type: "Granola Bars",
    price: "GHS 45.00",
    pieces: 120,
  },
  {
    productName: "Quaker Oats",
    type: "Instant Oatmeal",
    price: "GHS 65.99",
    pieces: 72,
  },
  {
    productName: "Lay's Classic",
    type: "Potato Chips",
    price: "GHS 30.50",
    pieces: 150,
  },
  {
    productName: "Oreo",
    type: "Chocolate Cookies",
    price: "GHS 55.00",
    pieces: 98,
  },
  {
    productName: "Tropicana",
    type: "Orange Juice",
    price: "GHS 75.25",
    pieces: 60,
  },
  {
    productName: "Snickers",
    type: "Chocolate Bars",
    price: "GHS 50.00",
    pieces: 110,
  },
  {
    productName: "Kellogg’s Corn Flakes",
    type: "Breakfast Cereal",
    price: "GHS 85.00",
    pieces: 70,
  },
  {
    productName: "Heinz",
    type: "Tomato Ketchup",
    price: "GHS 40.99",
    pieces: 130,
  },
  {
    productName: "Pepsi",
    type: "Soft Drink",
    price: "GHS 25.00",
    pieces: 200,
  },
  {
    productName: "Lipton",
    type: "Green Tea",
    price: "GHS 60.00",
    pieces: 90,
  },
  {
    productName: "Domino",
    type: "Sugar Packets",
    price: "GHS 35.75",
    pieces: 140,
  },
];

export const agentOrders = [
  {
    business_name: "Amazing Grace Enterprise",
    order_date: "March 24, 2025",
    products: 2,
    status: "Awaiting Approval",
    id: "42334",
  },
  {
    business_name: "Blue Horizon Logistics",
    order_date: "April 3, 2025",
    products: 5,
    status: "Approved",
    id: "353555",
  },
  {
    business_name: "Golden Fields Supplies",
    order_date: "March 18, 2025",
    products: 1,
    status: "Delivered",
    id: "234525",
  },
  {
    business_name: "Urban Essentials Co.",
    order_date: "May 1, 2025",
    products: 3,
    status: "Awaiting Approval",
    id: "23525",
  },
  {
    business_name: "Peak Performance Gear",
    order_date: "May 20, 2025",
    products: 4,
    status: "Approved",
    id: "52352",
  },
];

export const productData = [
  {
    id: 1,
    title: "Catalina Crunch",
    subtitle: "Peanut Butter Sandwich Cookies",
    weight: "4kg (Small)",
    price: "GHS 70.80",
  },
  {
    id: 2,
    title: "Heaven and Earth",
    subtitle: "Butter Date Cookies",
    weight: "4kg (Small)",
    price: "GHS 70.80",
  },
];
export const orderHistory = [
  {
    id: "order_001",
    initials: "MK",
    name: "Amazing Grace Enterprice",
    items: "1 Item(s)",
    status: "Approved",
    statusBg: "#F4FBF3",
    statusTextColor: "#2AB40E",
  },
  {
    id: "order_002",
    initials: "AG",
    name: "Amazing Grace Enterprice",
    items: "1 Item(s)",
    status: "Awaiting Approval",
    statusBg: "#EFF5FF",
    statusTextColor: "#6099FF",
  },
];


// mockdata.js
export const mockPurchaseOrders = [
  {
    id: "4814940",
    requestDate: "Mar 8, 2024",
    supplier: "Kola wholesale",
    customer: "John Doe",
    poNumber: "4500000433",
    totalCost: "2,000,000.00",
    deliveryDate: "Mar 10, 2023",
    approvalStatus: "Under review",
    paymentStatus: "Fully paid",
  },
  {
    id: "4814941",
    requestDate: "Mar 8, 2024",
    supplier: "Kola wholesale",
    customer: "John Doe",
    poNumber: "4500000433",
    totalCost: "2,000,000.00",
    deliveryDate: "Mar 10, 2023",
    approvalStatus: "Under review",
    paymentStatus: "Unpaid",
  },
  {
    id: "4814942",
    requestDate: "Mar 8, 2024",
    supplier: "Kola wholesale",
    customer: "John Doe",
    poNumber: "4500000433",
    totalCost: "2,000,000.00",
    deliveryDate: "Mar 10, 2023",
    approvalStatus: "Under review",
    paymentStatus: "Partially paid",
  },
  {
    id: "4814943",
    requestDate: "Mar 8, 2024",
    supplier: "Kola wholesale",
    customer: "John Doe",
    poNumber: "4500000433",
    totalCost: "2,000,000.00",
    deliveryDate: "Mar 10, 2023",
    approvalStatus: "Under review",
    paymentStatus: "Cash sale",
  },
];
